### ISSUE TITLE
Pairing fails with BLE device Feit LED bulb

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#136]
https://www.amazon.com/dp/B07J2FP389?psc=1&ref=ppx_yo2ov_dt_b_product_details

Feit Electric OM60/SW/HK 60W Equivalent A19 Smart, Works with Apple HomeKit and Siri Voice Control, No Hub Required LED Light Bulb, 4.4" H x 2.4" D, 2700K Soft White

‎OM60/SW/HK
--

<br class="Apple-interchange-newline">

```
2022-08-07 12:23:04.157 DEBUG (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing authentication failed
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/config_flow.py", line 464, in async_step_pair
    pairing = await self.finish_pairing(code)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 61, in _async_wrap
    return await func(*args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/discovery.py", line 147, in finish_pairing
    pairing = await drive_pairing_state_machine(
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 195, in drive_pairing_state_machine
    request, expected = state_machine.send(TLV.decode_bytes(response))
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 222, in perform_pair_setup_part2
    handle_state_step(response_tlv, TLV.M4)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 87, in handle_state_step
    error_handler(tlv_dict[TLV.kTLVType_Error], f"step {expected_state}")
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 61, in error_handler
    raise AuthenticationError(stage)
aiohomekit.exceptions.AuthenticationError: step bytearray(b'\x04')
```

**Comment by bdraco** [comment]
I've been messing with this for hours and I haven't been able to figure out why it rejects the code. Everything looks right.  I went through the srp code line by line and it all seems right.  

Pairs fine with iOS though

**Comment by bdraco** [comment]
After messing with it for hours, I changed the MTU to 100 it pairs

**Comment by bdraco** [comment]
I also had to increase the read timeout to 20s from 10s on macos

**Comment by Jc2k** [comment]
Oh god. I love that the error is an auth error.

**Comment by bdraco** [comment]
So we need to do three things

- [ ] Get bleak to know about the MTU in the char data
- [ ] Raise the timeout on mac yet again for reads
- [ ] Lower the MTU to 100 here until we get bleak to know about it

Sadly in the mean time thats going to make reconnects even slower but https://github.com/hbldh/bleak/pull/923 will speed that up

**Comment by Jc2k** [comment]
Sounds good 👍

**Comment by Djelibeybi** [comment]
Side: Feit Electric just ~saved~ bought LIFX. That's not relevant to this issue, but I thought it was interesting enough to share.

**Comment by bdraco** [comment]
The bleak PR to raise the timeout is merged.  Nothing more to track here. We will get the fix for macos when we bump bleak in HA
