### ISSUE TITLE
Pairing with a Cozylife 3 gang switch sometimes fails

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#152]
```
2022-08-14 13:14:15.371 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  1 (Identifier): (17 bytes/<class 'bytearray'>) 0x35423a32453a45303a38443a44373a3430
  3 (PublicKey): (32 bytes/<class 'bytearray'>) 0x0000000000000000000000000000000000000000000000000000000000000000
  10 (Signature): (64 bytes/<class 'bytearray'>) 0x74bd4c98f89b79a8a2882e4ad4deb910ad2770c9285c413ed7af8e65b7cc4fcbdf506a2990548f87aa322debc9a258dfa0fbedb9abfa8e0bb0f4f5d12f3a1f00
]
```

I'm going to guess the device sending a public key of 0000000 is a problem :)

```
2022-08-14 13:12:55.621 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.106.202: raw request: b'GET /characteristics?id=1.13 HTTP/1.1\r\nHost: 192.168.106.202\r\n\r\n'
2022-08-14 13:12:56.082 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.106.202: raw response: bytearray(b'{"characteristics":[{"aid":1,"iid":13,"value":false}]}')
2022-08-14 13:13:19.174 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.106.25: raw request: b'GET /characteristics?id=1.51 HTTP/1.1\r\nHost: 192.168.106.25\r\n\r\n'
2022-08-14 13:13:19.247 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.106.25: raw response: bytearray(b'{"characteristics":[{"aid":1,"iid":51,"value":1}]}')
2022-08-14 13:13:32.704 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.81: raw request: b'GET /characteristics?id=1.13 HTTP/1.1\r\nHost: 192.168.107.81\r\n\r\n'
2022-08-14 13:13:32.800 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.81: raw response: bytearray(b'{"characteristics":[{"aid":1,"iid":13,"value":false}]}')
2022-08-14 13:13:34.279 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.127: raw request: b'GET /characteristics?id=1.37,1.34,1.49,1.52,1.18,1.76,1.21,1.24,1.27,1.33,1.39,1.36,1.51,1.54,1.75,1.20,1.17,1.23,1.35,1.38,1.41,1.50,1.53,1.19,1.25,1.22 HTTP/1.1\r\nHost: 192.168.107.127\r\n\r\n'
2022-08-14 13:13:34.398 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.127: raw response: bytearray(b'{"characteristics":[{"aid":1,"iid":37,"value":27.8},{"aid":1,"iid":34,"value":20.6},{"aid":1,"iid":49,"value":1},{"aid":1,"iid":52,"value":100},{"aid":1,"iid":18,"value":2},{"aid":1,"iid":76,"value":0},{"aid":1,"iid":21,"value":1},{"aid":1,"iid":24,"value":53.0},{"aid":1,"iid":27,"value":"My ecobee"},{"aid":1,"iid":33,"value":0},{"aid":1,"iid":39,"value":27.8},{"aid":1,"iid":36,"value":17.8},{"aid":1,"iid":51,"value":0},{"aid":1,"iid":54,"value":"There may be a problem with the Cooling system.\\nFor the past 4 hours the thermostat has been callin"},{"aid":1,"iid":75,"value":1},{"aid":1,"iid":20,"value":25.6},{"aid":1,"iid":17,"value":0},{"aid":1,"iid":23,"value":20.6},{"aid":1,"iid":35,"value":25.6},{"aid":1,"iid":38,"value":18.3},{"aid":1,"iid":41,"value":"2014-01-03T00:00:00-10:00W"},{"aid":1,"iid":50,"value":0},{"aid":1,"iid":53,"value":0},{"aid":1,"iid":19,"value":22.4},{"aid":1,"iid":25,"value":36.0},{"aid":1,"iid":22,"value":25.6}]}')
2022-08-14 13:13:52.588 DEBUG (MainThread) [aiohomekit.controller.ble.controller] Discovery for hkid 5B:2E:E0:8D:D7:40 not found, waiting for advertisement with timeout: 30.0
2022-08-14 13:13:52.589 DEBUG (MainThread) [aiohomekit.controller.ip.connection] Starting reconnect loop to 192.168.107.146:80
2022-08-14 13:13:52.589 DEBUG (MainThread) [aiohomekit.controller.ip.connection] Attempting connection to 192.168.107.146:80
2022-08-14 13:13:52.624 DEBUG (MainThread) [aiohomekit.protocol] #1 ios -> accessory: send SRP start request
2022-08-14 13:13:52.624 DEBUG (MainThread) [aiohomekit.protocol.tlv] sending [
  6 (State): (1 bytes/<class 'bytearray'>) 0x01
  0 (Method): (1 bytes/<class 'bytearray'>) 0x00
]

2022-08-14 13:13:52.624 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.146: raw request: b'POST /pair-setup HTTP/1.1\r\nHost: 192.168.107.146\r\nContent-Length: 6\r\nContent-Type: application/pairing+tlv8\r\n\r\n\x06\x01\x01\x00\x01\x00'
2022-08-14 13:13:52.769 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.146: raw response: bytearray(b'\x06\x01\x02\x03\xffU5\x93\x16\x05\x8d\xb7i\xd9"`\xd7\xbaq\xcf\xe9\x16v7\xaf,\xb6/\x1d\xb8\xbcN\x19\xc3"q\xf5\xbbP:e.?\x15=t*\x95\xcf\xab\x92\x80\xee(\xf9.\xa2\xac\xa7\x89\xbc\x1b\x7f\x15\xf8\x8f\x9ek\x9b\xd5\xfe?\xb3\xcc\xc6\xfb\x03\xc4b\xe6u\xafU\xb5/\x91\xdb\xf5)\x904b\x1a\x84\x12\x9bH~\x1f\xb8)\x03g\xbb\x1f\x81\xfd\xd9\xceh\x13\xe3\xc6\xf4\xf4e\x95y;\xcb\x9b\x15g\xeb\xb4 \xd3\x8bPL\xab\x18\xd14gE\xa4\x89\x83/\xa6I\xff\xd8\x93\xb9\xe2\xd1K<#I\xdb\xcb\x8b\xd3\n\x11LP\x1a\xa9(\xdd\xcf\x96\xc3\xd1\xc0\xbd\x11\xab\xecS\x14\xae\xabhn\x98\xfb\x1a(\xf5\x94\xfc\xf7Emg\xd3\xf6\x89\xd0\x0b0NzA\xd0{\x1f\xfa_w\x1c\xca\x8cw\xfd\x0f+\xcc\xe0\x97\xd17=\x8f\xbb\xc3i\xef\xfd\x94\x02\x15Q0\x18\xc7\x8f\\\xd8.\xc14\x92\xa7C[\xe9\xac\x04\xe3X\x10.`\x9f\xca\xc6N\xb7\x8f$I\xdc\xa3e\x03\x81}\xddd\x86\xc0\xc4z\xd8[\x9b\xc5Z\x02\x88\xceJ\x92\xd5\xda\xeb\xe9\\k\xf3I \x94q\x81\xbc4\x98(\xb0\xff^\xbe\x04\x02\xef\x8a\x81\xb6\x98\xc7\xefw?y\x1d52D\x9db\xf6"\xc5\xaf\xcc`\t\xbcxA\xbfB\xc1\x08\x9d\x1a\x03\x1d\xb0\xaa\xee\n\xa7:1\x8f_\xc4\x91\x8d\xa7\x8d\x03\xb3\xcd\xa5\x96{*<\x7f\xac7\x0b*\xa7\xaap^\x97\xb4\x89\xa8\xe0\x10FA\x9eF\x8a\xc3#4\xde\xd7B\x8d\xa5\xab\xf63ds\x86\x02\x10\x18\x1a5\x00\x1e\xe2\xf7?-\\\xa5[M\x14@\x8b')
2022-08-14 13:13:52.770 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  6 (State): (1 bytes/<class 'bytearray'>) 0x02
  3 (PublicKey): (384 bytes/<class 'bytearray'>) 0x55359316058db769d92260d7ba71cfe9167637af2cb62f1db8bc4e19c32271f5bb503a652e3f153d742a95cfab9280ee28f92ea2aca789bc1b7f15f88f9e6b9bd5fe3fb3ccc6fb03c462e675af55b52f91dbf5299034621a84129b487e1fb8290367bb1f81fdd9ce6813e3c6f4f46595793bcb9b1567ebb420d38b504cab18d1346745a489832fa649ffd893b9e2d14b3c2349dbcb8bd30a114c501aa928ddcf96c3d1c0bd11abec5314aeab686e98fb1a28f594fcf7456d67d3f689d00b304e7a41d07b1ffa5f771cca8c77fd0f2bcce097d1373d8fbbc369effd940215513018c78f5cd82ec13492a7435be9ac04e358102e609fcac64eb78f2449dca3657ddd6486c0c47ad85b9bc55a0288ce4a92d5daebe95c6bf34920947181bc349828b0ff5ebe0402ef8a81b698c7ef773f791d3532449d62f622c5afcc6009bc7841bf42c1089d1a031db0aaee0aa73a318f5fc4918da78d03b3cda5967b2a3c7fac370b2aa7aa705e97b489a8e01046419e468ac32334ded7428da5abf633647386
  2 (Salt): (16 bytes/<class 'bytearray'>) 0x181a35001ee2f73f2d5ca55b4d14408b
]

2022-08-14 13:13:52.770 DEBUG (MainThread) [aiohomekit.protocol] #3 ios -> accessory: send SRP verify request
2022-08-14 13:13:55.621 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.106.202: raw request: b'GET /characteristics?id=1.13 HTTP/1.1\r\nHost: 192.168.106.202\r\n\r\n'
2022-08-14 13:13:55.670 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.106.202: raw response: bytearray(b'{"characteristics":[{"aid":1,"iid":13,"value":false}]}')
2022-08-14 13:14:04.999 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new device_tracker.bluetooth_le_tracker entity: device_tracker.e922ebea_552d_b43d_b2c5_e232c3ced028
2022-08-14 13:14:14.615 DEBUG (MainThread) [aiohomekit.protocol.tlv] sending [
  6 (State): (1 bytes/<class 'bytearray'>) 0x03
  3 (PublicKey): (384 bytes/<class 'bytes'>) b"\xec\xf77\xe2\x95X\x96\xf7\x95\x8fK|\xa4\x84\xd8\xf2\xa5\xa7\xba\x97\x99\x0fB\xd3R\xb8\xbe\xad\x95\xe3\xd4\x08Dq\xc5\xa6\x92\x89\ru\x02'%^]\x9c\xaen\x03L\xb4q\x9bU|\xa3\xd7\xb0\xac)\xe0\x0ba\x17O \x08*+\xe7\x83\x8f\xbce&O\xa7'\x14\xc39\x9b\x80wU\tGr\x80yRXoL\xd0\xd5\xcf5_LN/\x04\x89p\xdd\xef;\xe4\x83J\x81sg\xd3\xb2\x9f\xd3\x08b \xc3\x1d]\x80\xc44\xb1H\xc5l\x04A=\x89\x8a\x98\xc0\x8at,z\xa7P\xf1i\xadA@]\x0f\x97\xc6^\x0e\x8a\t1\xda\x98\xe6F\xc7H\x80<R\xb8\x1c\x9d\xad\xc2jV\xa9\x1e\x1b$(hP\xbc\x9f\xc1\xe1H\x9a\xdf&\xaeu\x02\x15\xc6\x9fR\xcc\xc7t\xa3\xfe\xecJ\xb8\xa1\x97\x8b\x01\xd5\x95.\x97\xa4 \xcac\xe9aSQa]fl\xb3\xde\x91zOG\x87X\x14U\xd3x\x02\xfa\xb0\x01U\xf2\xb09q\x81\x83\x9a\x020\xe7\xb7\xe3\x10\xa8\x90&\x1f\xafYL\xfd\xd9X5p\xac;D6\x97\xb6\x07\xd6\xffDG\x98\xedmnr`M\x00\x04|\x07\x96\xd9\xcb\x82T\x94\xef*\x08[\xd3W\x0c\xed\xb4\x0f\xce\xfa2Z\xe2\xa5\xdd{\x84\n\xa3\x8f#\x9c\xcf\x86w-\xfdo\xfb\xad\xd8\xc4\xccW\x13\xa0YS4\xdfY\\\xf0b\x14WP\xfc\xbaA\xfc\xd5VXf\x05{\xdc|\x1ck6\xfb\xfeXR\xef\xfc\\\x9c\xcd\xe9\x8a:\x81im\xed\x12I\xdb\xc2\x16\xe5\xe1\xf5s\xba"
  4 (Proof): (64 bytes/<class 'bytes'>) b"\xcf$\xa4uu\xca\xb6\xe6\x0b)\xd6=\xee\x1d\x9dO\x91xAg|\x82F\xcd\xe9\xa9\xb0\xa3I\xd4\xd9\x0cJW\xbf\x14\x15,u\xab!8\xc6y\x17Y\x9cy\x88\x1c]\xc8h't\x97x`\xf6\xb9\x1e-O\x92"
]

2022-08-14 13:14:14.615 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.146: raw request: b"POST /pair-setup HTTP/1.1\r\nHost: 192.168.107.146\r\nContent-Length: 457\r\nContent-Type: application/pairing+tlv8\r\n\r\n\x06\x01\x03\x03\xff\xec\xf77\xe2\x95X\x96\xf7\x95\x8fK|\xa4\x84\xd8\xf2\xa5\xa7\xba\x97\x99\x0fB\xd3R\xb8\xbe\xad\x95\xe3\xd4\x08Dq\xc5\xa6\x92\x89\ru\x02'%^]\x9c\xaen\x03L\xb4q\x9bU|\xa3\xd7\xb0\xac)\xe0\x0ba\x17O \x08*+\xe7\x83\x8f\xbce&O\xa7'\x14\xc39\x9b\x80wU\tGr\x80yRXoL\xd0\xd5\xcf5_LN/\x04\x89p\xdd\xef;\xe4\x83J\x81sg\xd3\xb2\x9f\xd3\x08b \xc3\x1d]\x80\xc44\xb1H\xc5l\x04A=\x89\x8a\x98\xc0\x8at,z\xa7P\xf1i\xadA@]\x0f\x97\xc6^\x0e\x8a\t1\xda\x98\xe6F\xc7H\x80<R\xb8\x1c\x9d\xad\xc2jV\xa9\x1e\x1b$(hP\xbc\x9f\xc1\xe1H\x9a\xdf&\xaeu\x02\x15\xc6\x9fR\xcc\xc7t\xa3\xfe\xecJ\xb8\xa1\x97\x8b\x01\xd5\x95.\x97\xa4 \xcac\xe9aSQa]fl\xb3\xde\x91zOG\x87X\x14U\xd3x\x02\xfa\xb0\x01U\xf2\xb09q\x81\x83\x9a\x020\xe7\xb7\xe3\x10\xa8\x03\x81\x90&\x1f\xafYL\xfd\xd9X5p\xac;D6\x97\xb6\x07\xd6\xffDG\x98\xedmnr`M\x00\x04|\x07\x96\xd9\xcb\x82T\x94\xef*\x08[\xd3W\x0c\xed\xb4\x0f\xce\xfa2Z\xe2\xa5\xdd{\x84\n\xa3\x8f#\x9c\xcf\x86w-\xfdo\xfb\xad\xd8\xc4\xccW\x13\xa0YS4\xdfY\\\xf0b\x14WP\xfc\xbaA\xfc\xd5VXf\x05{\xdc|\x1ck6\xfb\xfeXR\xef\xfc\\\x9c\xcd\xe9\x8a:\x81im\xed\x12I\xdb\xc2\x16\xe5\xe1\xf5s\xba\x04@\xcf$\xa4uu\xca\xb6\xe6\x0b)\xd6=\xee\x1d\x9dO\x91xAg|\x82F\xcd\xe9\xa9\xb0\xa3I\xd4\xd9\x0cJW\xbf\x14\x15,u\xab!8\xc6y\x17Y\x9cy\x88\x1c]\xc8h't\x97x`\xf6\xb9\x1e-O\x92"
2022-08-14 13:14:14.943 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.146: raw response: bytearray(b"\x06\x01\x04\x04@\x92O\xbc\xe4\x03\xb1/\x13F\xdfpO\x10H\x9d\x9e2\xb7\xc3\xcb\xff\t\'E\x8a:L\xb6\xea\n\xbcC\xa5\x8e\x1fi=0\\\x08\xd6\xf2zr?cG\xa9;T\xaa\x81\xe9`\xad\xa8qL\xff\xa3\xe6f2\x0f\x05\x1a\xbc\x04P\x91Rp\xa6\xbf\x9f;\xe1\xbe\x8b$i\xc2\tC\x84\xc5\xc0\xaa\xbf\xf7\r\x91")
2022-08-14 13:14:14.943 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  6 (State): (1 bytes/<class 'bytearray'>) 0x04
  4 (Proof): (64 bytes/<class 'bytearray'>) 0x924fbce403b12f1346df704f10489d9e32b7c3cbff0927458a3a4cb6ea0abc43a58e1f693d305c08d6f27a723f6347a93b54aa81e960ada8714cffa3e666320f
  5 (EncryptedData): (26 bytes/<class 'bytearray'>) 0xbc0450915270a6bf9f3be1be8b2469c2094384c5c0aabff70d91
]

2022-08-14 13:14:14.943 DEBUG (MainThread) [aiohomekit.protocol] #5 ios -> accessory: send SRP exchange request
2022-08-14 13:14:15.136 DEBUG (MainThread) [aiohomekit.protocol.tlv] sending [
  1 (Identifier): (36 bytes/<class 'bytes'>) b'a8445b03-0802-4894-98eb-962429cfa37a'
  3 (PublicKey): (32 bytes/<class 'bytes'>) b"^\x9c\xa9\xaf\x9a2{\xa1\x04\xe4\xbep\xbe\xed\xe3b\xc0\xc0+\x81\x0fO\xc1\xf9L\xa7'>O11\xa5"
  10 (Signature): (64 bytes/<class 'bytes'>) b'\x82j\xb6\x8f\t\xb6\xd6-\x05l|\xe87\xdb\x18\xc0\t\x02\x80\xf6\xf6spN/\xbc1\x8f\x94\xcd\x1e\\\xd0\xbbL\x063\xefd\xeb\xb5d8]\xc7ij\x95\x1f\x03f\x94D\xd3\xaf\xcdD\x1e\x99u\xdf&H\x02'
]

2022-08-14 13:14:15.136 DEBUG (MainThread) [aiohomekit.protocol.tlv] sending [
  6 (State): (1 bytes/<class 'bytearray'>) 0x05
  5 (EncryptedData): (154 bytes/<class 'bytes'>) b'\xf5\xf4{\x98\x8a^\x81l\xf7z~r\xa3\x06\xf3\x0b(\xd8\xd5l\xf5\xb4\x925\xdf\xe6S\x14\xeb\xf4\xe8\xc6xE>\x1d\x9e\xab\x1a\x05\x13\x12\x11V`\xd2\xb0\xc3\xb4\x8fwY\xeeRh|\xe3\x985\x12\xbfl/\n\xdc\x11+~\xdf\x91\x84\x16\xa7\x1e\xdd\xe1-e\xe2\xa4\xca\xc2\x1f\x94B\xa9\xa4_\x1ab\x849\xc8\x8a]\x10s\x97\x9e\xb5MrK\x89\xf7\xdd\xd0\xcby\xf9\xb0\xcf\xff\xc2\xe3\xa3]D\xdd\xf2\xafx\xc0\xc7\xa1X\xcfDB\xdd\x08\xe3X\xd9\xcc^\xcb6j\x80\x8f\x8b,dN\xc1\x85E\xf9,\xe5Z\xb3\x07'
]

2022-08-14 13:14:15.136 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.146: raw request: b'POST /pair-setup HTTP/1.1\r\nHost: 192.168.107.146\r\nContent-Length: 159\r\nContent-Type: application/pairing+tlv8\r\n\r\n\x06\x01\x05\x05\x9a\xf5\xf4{\x98\x8a^\x81l\xf7z~r\xa3\x06\xf3\x0b(\xd8\xd5l\xf5\xb4\x925\xdf\xe6S\x14\xeb\xf4\xe8\xc6xE>\x1d\x9e\xab\x1a\x05\x13\x12\x11V`\xd2\xb0\xc3\xb4\x8fwY\xeeRh|\xe3\x985\x12\xbfl/\n\xdc\x11+~\xdf\x91\x84\x16\xa7\x1e\xdd\xe1-e\xe2\xa4\xca\xc2\x1f\x94B\xa9\xa4_\x1ab\x849\xc8\x8a]\x10s\x97\x9e\xb5MrK\x89\xf7\xdd\xd0\xcby\xf9\xb0\xcf\xff\xc2\xe3\xa3]D\xdd\xf2\xafx\xc0\xc7\xa1X\xcfDB\xdd\x08\xe3X\xd9\xcc^\xcb6j\x80\x8f\x8b,dN\xc1\x85E\xf9,\xe5Z\xb3\x07'
2022-08-14 13:14:15.370 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.146: raw response: bytearray(b'\x06\x01\x06\x05\x87t\xa2\x0e\xa7\x14\xf4d\x8a\x7f+& \xc8\xd0YT-V1\x00\xb4>"\xb2\xbe\xd3\xb4\x86\r\xddiss\x8c\r\xa52\xb6\xcb\x86\xf4S-\xfa\xcb\xa8\x05S#\x9f\xe8\x9c,\xd4Z\x05\x99X\x9b r\x13T\xc0\xec{\xe78\x1fQ\x8d\xed\xd2v4\x91\xd3\x1cO\x84\xd6\x0e\xc36\xfb\xd9\xb8\xa5b\x0c\xff\xda\xf0\x9e\x80-\x88d\x14\xe95\x0e\xbb)":\x13\x82\xf0\xf4\x85\x89\xb1\x1e\xaa\x84J\xe2\x1a\x14\xd3\x9f\xa3"\xa1Z\x11\x1c\x187\x88=z\x8c\x83')
2022-08-14 13:14:15.370 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  6 (State): (1 bytes/<class 'bytearray'>) 0x06
  5 (EncryptedData): (135 bytes/<class 'bytearray'>) 0x74a20ea714f4648a7f2b2620c8d059542d563100b43e22b2bed3b4860ddd6973738c0da532b6cb86f4532dfacba80553239fe89c2cd45a0599589b20721354c0ec7be7381f518dedd2763491d31c4f84d60ec336fbd9b8a5620cffdaf09e802d886414e9350ebb29223a1382f0f48589b11eaa844ae21a14d39fa322a15a111c1837883d7a8c83
]

2022-08-14 13:14:15.371 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  1 (Identifier): (17 bytes/<class 'bytearray'>) 0x35423a32453a45303a38443a44373a3430
  3 (PublicKey): (32 bytes/<class 'bytearray'>) 0x0000000000000000000000000000000000000000000000000000000000000000
  10 (Signature): (64 bytes/<class 'bytearray'>) 0x74bd4c98f89b79a8a2882e4ad4deb910ad2770c9285c413ed7af8e65b7cc4fcbdf506a2990548f87aa322debc9a258dfa0fbedb9abfa8e0bb0f4f5d12f3a1f00
]

2022-08-14 13:14:15.458 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 337, in perform_pair_setup_part2
    e25519s.verify(bytes(accessory_sig), bytes(accessory_info))
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/ed25519.py", line 73, in verify
    raise exceptions.InvalidSignature
cryptography.exceptions.InvalidSignature

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/config_flow.py", line 464, in async_step_pair
    pairing = await self.finish_pairing(code)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ip/discovery.py", line 88, in finish_pairing
    request, expected = state_machine.send(response)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 339, in perform_pair_setup_part2
    raise InvalidSignatureError("step #7")
aiohomekit.exceptions.InvalidSignatureError: step #7
2022-08-14 13:14:15.462 DEBUG (MainThread) [aiohomekit.controller.ble.controller] Discovery for hkid 5B:2E:E0:8D:D7:40 not found, waiting for advertisement with timeout: 30.0
2022-08-14 13:14:15.465 DEBUG (MainThread) [aiohomekit.protocol] #1 ios -> accessory: send SRP start request
2022-08-14 13:14:15.465 DEBUG (MainThread) [aiohomekit.protocol.tlv] sending [
  6 (State): (1 bytes/<class 'bytearray'>) 0x01
  0 (Method): (1 bytes/<class 'bytearray'>) 0x00
]

2022-08-14 13:14:15.465 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.146: raw request: b'POST /pair-setup HTTP/1.1\r\nHost: 192.168.107.146\r\nContent-Length: 6\r\nContent-Type: application/pairing+tlv8\r\n\r\n\x06\x01\x01\x00\x01\x00'
2022-08-14 13:14:15.569 DEBUG (MainThread) [aiohomekit.controller.ip.connection] 192.168.107.146: raw response: bytearray(b'\x06\x01\x02\x07\x01\x06')
2022-08-14 13:14:15.569 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  6 (State): (1 bytes/<class 'bytearray'>) 0x02
  7 (Error): (1 bytes/<class 'bytearray'>) 0x06 [Unavailable]
]


```

**Comment by bdraco** [comment]
It paired the second time, so might just be a flakey device

**Comment by bdraco** [comment]
This was an SRP issue which was already fixed
