### ISSUE TITLE
Pairing with new Belkin Wemo WDS070 Smart Dimmer fails

### ISSUE THREAD

**Issue by braker1nine** [Jc2k/aiohomekit#157]
I bought [this dimmer](https://www.belkin.com/us/smart-home/wemo/smart-dimmer/p/p-wds070/) which touts itself as a HomeKit only Thread dimmer with Bluetooth. I picked it up just to see how Home Assistant would handle it. I hoped at least it might connect via Bluetooth. Sadly it looks like I'm getting pairing error...

```
Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 465, in async_step_pair
    return await self._entry_from_accessory(pairing)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 589, in _entry_from_accessory
    name = await pairing.get_primary_name()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/abstract.py", line 143, in get_primary_name
    accessories = await self.list_accessories_and_characteristics()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 103, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 65, in _async_wrap
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 529, in list_accessories_and_characteristics
    await self._populate_accessories_and_characteristics()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 621, in _populate_accessories_and_characteristics
    await self._populate_char_values(config_changed)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 551, in _populate_char_values
    results = await self._get_characteristics_while_connected(chars)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 747, in _get_characteristics_while_connected
    data = await self._async_request_under_lock(OpCode.CHAR_READ, char)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 295, in _async_request_under_lock
    raise_for_pdu_status(self.client, pdu_status)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 206, in raise_for_pdu_status
    raise ValueError(
ValueError: C3:28:A0:79:0E:7D: PDU status was not success: Invalid request (6)
```

Also apologies if I'm raising this issue in the wrong place 🙏 I'm happy to take it somewhere else and/or try to provide any more detailed logs if I can.

**Comment by bdraco** [comment]
Did you try updating the firmware or factory resetting it and trying again? Sometimes new devices have issues with the stack. If you can’t get it to pair after doing that I’ll try to pick one up and see if I can replicate it

**Comment by braker1nine** [comment]
I can't find any information from Belkin about the firmware versions. For whatever it's worth, I've currently got it paired directly with HomeKit, it claims it's up to date.

I gave resetting and repairing a few tries with no luck

**Comment by bdraco** [comment]
I'll see if I can pick one up next week

**Comment by bdraco** [comment]
```

2022-08-25 12:22:26.667 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Dimmer 614 [E0:FD:4A:7B:C2:EF] (id=78:CC:65:D1:E6:82): Read characteristic got data, expected format is data: data=bytearray(b'\x01\x00') decoded=bytearray(b'')
2022-08-25 12:22:26.667 DEBUG (MainThread) [aiohomekit.controller.ble.client] E0:FD:4A:7B:C2:EF: Bleak obj MTU: 247, client.mtu_size: 100
2022-08-25 12:22:26.667 DEBUG (MainThread) [aiohomekit.controller.ble.client] E0:FD:4A:7B:C2:EF: Using fragment size: 228
2022-08-25 12:22:26.667 DEBUG (MainThread) [aiohomekit.controller.ble.client] Queuing fragment for write: b'\x00\x03\x0f\xf2\x00'
2022-08-25 12:22:26.847 DEBUG (MainThread) [aiohomekit.controller.ble.client] Read fragment: bytearray(b'\x02\x0f\x00\r\x00\x01\x0b\x01\t\x01\x01\x01\x02\x04\x00\x04\x00\x00')
2022-08-25 12:22:26.847 DEBUG (MainThread) [aiohomekit.pdu] Got PDU 2: TID 0f (Expected: 0f), Status:0, Len:13
2022-08-25 12:22:26.847 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  1 (Identifier): (11 bytes/<class 'bytearray'>) 0x0109010101020400040000
]

2022-08-25 12:22:26.847 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Dimmer 614 [E0:FD:4A:7B:C2:EF] (id=78:CC:65:D1:E6:82): Read characteristic got data, expected format is data: data=bytearray(b'\x01\x0b\x01\t\x01\x01\x01\x02\x04\x00\x04\x00\x00') decoded=bytearray(b'\x01\t\x01\x01\x01\x02\x04\x00\x04\x00\x00')
2022-08-25 12:22:26.847 DEBUG (MainThread) [aiohomekit.controller.ble.client] E0:FD:4A:7B:C2:EF: Bleak obj MTU: 247, client.mtu_size: 100
2022-08-25 12:22:26.847 DEBUG (MainThread) [aiohomekit.controller.ble.client] E0:FD:4A:7B:C2:EF: Using fragment size: 228
2022-08-25 12:22:26.848 DEBUG (MainThread) [aiohomekit.controller.ble.client] Queuing fragment for write: b'\x00\x03\x8f\xf3\x00'
2022-08-25 12:22:27.028 DEBUG (MainThread) [aiohomekit.controller.ble.client] Read fragment: bytearray(b'\x02\x8f\x06')
2022-08-25 12:22:27.028 DEBUG (MainThread) [aiohomekit.pdu] Got PDU 2: TID 8f (Expected: 8f), Status:6, Len:-2
2022-08-25 12:22:27.028 WARNING (MainThread) [aiohomekit.pdu] Transaction 143 failed with error 6 (Invalid request)
2022-08-25 12:22:27.037 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 442, in async_step_pair
    return await self._entry_from_accessory(pairing)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 566, in _entry_from_accessory
    name = await pairing.get_primary_name()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/abstract.py", line 208, in get_primary_name
    accessories = await self.list_accessories_and_characteristics()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 103, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 66, in _async_wrap
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 511, in list_accessories_and_characteristics
    await self._populate_accessories_and_characteristics()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 600, in _populate_accessories_and_characteristics
    await self._populate_char_values(config_changed)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 533, in _populate_char_values
    results = await self._get_characteristics_while_connected(chars)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 726, in _get_characteristics_while_connected
    data = await self._async_request_under_lock(OpCode.CHAR_READ, char)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 280, in _async_request_under_lock
    raise_for_pdu_status(self.client, pdu_status)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 207, in raise_for_pdu_status
    raise ValueError(
ValueError: E0:FD:4A:7B:C2:EF: PDU status was not success: Invalid request (6)
2022-08-25 12:22:27.040 DEBUG (MainThread) [aiohomekit.controller.ble.controller] Discovery for 78:cc:65:d1:e6:82 already found
2022-08-25 12:22:27.040 DEBUG (MainThread) [aiohomekit.controller.ble.discovery] Wemo Dimmer 614 (E0:FD:4A:7B:C2:EF): Ensure connected with device E0:FD:4A:7B:C2:EF: Wemo Dimmer 614; rssi=-54
2022-08-25 12:22:27.040 DEBUG (MainThread) [aiohomekit.controller.ble.client] E0:FD:4A:7B:C2:EF: Bleak obj MTU: 247, client.mtu_size: 100
2022-08-25 12:22:27.040 DEBUG (MainThread) [aiohomekit.controller.ble.client] E0:FD:4A:7B:C2:EF: Using fragment size: 244
2022-08-25 12:22:27.040 DEBUG (MainThread) [aiohomekit.controller.ble.client] Queuing fragment for write: b'\x00\x03\xd5$\x00'
2022-08-25 12:22:27.252 DEBUG (MainThread) [aiohomekit.controller.ble.client] Read fragment: bytearray(b'\x02\xd5\x00\x03\x00\x01\x01\x02')
2022-08-25 12:22:27.253 DEBUG (MainThread) [aiohomekit.pdu] Got PDU 2: TID d5 (Expected: d5), Status:0, Len:3
2022-08-25 12:22:27.253 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  1 (Identifier): (1 bytes/<class 'bytearray'>) 0x02
]

2022-08-25 12:22:27.253 DEBUG (MainThread) [aiohomekit.controller.ble.discovery] Wemo Dimmer 614 (E0:FD:4A:7B:C2:EF): starting pairing; rssi=-54
2022-08-25 12:22:27.253 DEBUG (MainThread) [aiohomekit.protocol] #1 ios -> accessory: send SRP start request
2022-08-25 12:22:27.253 DEBUG (MainThread) [aiohomekit.protocol.tlv] sending [
  6 (State): (1 bytes/<class 'bytearray'>) 0x01
  0 (Method): (1 bytes/<class 'bytearray'>) 0x00
]

2022-08-25 12:22:27.253 DEBUG (MainThread) [aiohomekit.controller.ble.client] E0:FD:4A:7B:C2:EF: Bleak obj MTU: 247, client.mtu_size: 100
2022-08-25 12:22:27.253 DEBUG (MainThread) [aiohomekit.controller.ble.client] E0:FD:4A:7B:C2:EF: Using fragment size: 244
2022-08-25 12:22:27.253 DEBUG (MainThread) [aiohomekit.controller.ble.client] Queuing fragment for write: b'\x00\x02q"\x00\x0b\x00\t\x01\x01\x01\x06\x06\x01\x01\x00\x01\x00'
2022-08-25 12:22:27.477 DEBUG (MainThread) [aiohomekit.controller.ble.client] Read fragment: bytearray(b'\x02q\x00\x08\x00\x01\x06\x06\x01\x02\x07\x01\x06')
2022-08-25 12:22:27.477 DEBUG (MainThread) [aiohomekit.pdu] Got PDU 2: TID 71 (Expected: 71), Status:0, Len:8
2022-08-25 12:22:27.477 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  1 (Identifier): (6 bytes/<class 'bytearray'>) 0x060102070106
]

2022-08-25 12:22:27.477 DEBUG (MainThread) [aiohomekit.protocol.tlv] receiving [
  6 (State): (1 bytes/<class 'bytearray'>) 0x02
  7 (Error): (1 bytes/<class 'bytearray'>) 0x06 [Unavailable]
]

2022-08-25 12:22:27.477 DEBUG (MainThread) [aiohomekit.protocol] #3 ios -> accessory: send SRP verify request
2022-08-25 12:22:39.399 DEBUG (MainThread) [homeassistant.components.homekit_controller.config_flow] Discovered device Sensibo-53B1CC (Sensibo Air - 52:70:89:CC:35:98)
2022-08-25 12:22:39.400 DEBUG (MainThread) [homeassistant.components.homekit_controller.config_flow] HomeKit device 52:70:89:CC:35:98 ignored as already paired
2022-08-25 12:22:57.268 DEBUG (MainThread) [aiohomekit.controller.ble.discovery] Wemo Dimmer 614 (E0:FD:4A:7B:C2:EF): Session closed callback; rssi=-54
2022-08-25 12:22:57.305 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Dimmer 614 [E0:FD:4A:7B:C2:EF] (id=78:CC:65:D1:E6:82): Description updated: old=HomeKitAdvertisement(name='Wemo Dimmer 614', id='78:cc:65:d1:e6:82', status_flags=<StatusFlags.UNPAIRED: 1>, config_num=1, category=<Categories.LIGHTBULB: 5>, setup_hash=b'wg\xb3K', address='E0:FD:4A:7B:C2:EF', state_num=1) new=HomeKitAdvertisement(name='Wemo Dimmer 614', id='78:cc:65:d1:e6:82', status_flags=<StatusFlags.0: 0>, config_num=1, category=<Categories.LIGHTBULB: 5>, setup_hash=b'wg\xb3K', address='E0:FD:4A:7B:C2:EF', state_num=1)
2022-08-25 12:22:57.306 DEBUG (MainThread) [aiohomekit.controller.abstract] Wemo Dimmer 614 [E0:FD:4A:7B:C2:EF] (id=78:CC:65:D1:E6:82): Description updated: old=HomeKitAdvertisement(name='Wemo Dimmer 614', id='78:cc:65:d1:e6:82', status_flags=<StatusFlags.UNPAIRED: 1>, config_num=1, category=<Categories.LIGHTBULB: 5>, setup_hash=b'wg\xb3K', address='E0:FD:4A:7B:C2:EF', state_num=1) new=HomeKitAdvertisement(name='Wemo Dimmer 614', id='78:cc:65:d1:e6:82', status_flags=<StatusFlags.0: 0>, config_num=1, category=<Categories.LIGHTBULB: 5>, setup_hash=b'wg\xb3K', address='E0:FD:4A:7B:C2:EF', state_num=1)
2022-08-25 12:22:57.306 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Dimmer 614 [E0:FD:4A:7B:C2:EF] (id=78:CC:65:D1:E6:82): BLE device changed from E0:FD:4A:7B:C2:EF (/org/bluez/hci0/dev_E0_FD_4A_7B_C2_EF) [rssi:-54] to E0:FD:4A:7B:C2:EF (/org/bluez/hci1/dev_E0_FD_4A_7B_C2_EF) [rssi:-60]; closing connection

```
Fails for me as well

**Comment by bdraco** [comment]
```
2022-08-25 12:32:58.840 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Dimmer 614 [A3B9AAA9-9E14-CF76-8BE8-6445A583B1C4] (id=3E:E6:09:DE:A7:B1): Reading characteristic 00000131-0000-1000-8000-0026BB765291
2022-08-25 12:32:58.840 DEBUG (MainThread) [aiohomekit.controller.ble.client] A3B9AAA9-9E14-CF76-8BE8-6445A583B1C4: No bleak obj MTU or max_write_without_response_size, using client.mtu_size-3: 244
2022-08-25 12:32:58.840 DEBUG (MainThread) [aiohomekit.controller.ble.client] A3B9AAA9-9E14-CF76-8BE8-6445A583B1C4: Using fragment size: 228
2022-08-25 12:32:58.840 DEBUG (MainThread) [aiohomekit.controller.ble.client] Queuing fragment for write: b'\x00\x03\x90\xf3\x00'
2022-08-25 12:32:58.898 DEBUG (MainThread) [aiohomekit.controller.ble.client] Read fragment: bytearray(b'\x02\x90\x06')
2022-08-25 12:32:58.898 DEBUG (MainThread) [aiohomekit.pdu] Got PDU 2: TID 90 (Expected: 90), Status:6, Len:-2
2022-08-25 12:32:58.898 WARNING (MainThread) [aiohomekit.pdu] Transaction 144 failed with error 6 (Invalid request)

```

Its failing on `00000131-0000-1000-8000-0026BB765291`

**Comment by bdraco** [comment]
`Setup Data Stream Transport`

**Comment by bdraco** [comment]
Its also got a vendor one that fails as well
```
2022-08-25 12:42:58.739 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Dimmer 614 [246912DC-8FA3-82ED-DEA4-9EB91D8FC2EE] (id=CB:1E:55:86:B9:DA): Read characteristic 00000037-0000-1000-8000-0026BB765291 got data, expected format is string: data=bytearray(b'\x01\x031.0') decoded=bytearray(b'1.0')
2022-08-25 12:42:58.739 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Wemo Dimmer 614 [246912DC-8FA3-82ED-DEA4-9EB91D8FC2EE] (id=CB:1E:55:86:B9:DA): Reading characteristic 00000138-0000-1000-8000-0026BB765291
2022-08-25 12:42:58.739 DEBUG (MainThread) [aiohomekit.controller.ble.client] 246912DC-8FA3-82ED-DEA4-9EB91D8FC2EE: No bleak obj MTU or max_write_without_response_size, using client.mtu_size-3: 244
2022-08-25 12:42:58.739 DEBUG (MainThread) [aiohomekit.controller.ble.client] 246912DC-8FA3-82ED-DEA4-9EB91D8FC2EE: Using fragment size: 228

```

**Comment by bdraco** [comment]
Change should appear in Home Assistant 2022.9.x
