### ISSUE TITLE
If we a device roams between bluetooth adapters we need to clear the services cache

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#158]
```
2022-08-17 18:41:44.899 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472599046320] [org.bluez.Error.Failed] Not connected
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1717, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1754, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/switch.py", line 81, in async_turn_off
    await self.async_put_characteristics({CharacteristicsTypes.ON: False})
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/entity.py", line 91, in async_put_characteristics
    return await self._accessory.put_characteristics(payload)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 633, in put_characteristics
    results = await self.pairing.put_characteristics(characteristics)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 103, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 66, in _async_wrap
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 776, in put_characteristics
    await self._populate_accessories_and_characteristics()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 618, in _populate_accessories_and_characteristics
    await self._async_pair_verify()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 393, in _async_pair_verify
    session_id, derive = await drive_pairing_state_machine(
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 289, in drive_pairing_state_machine
    iid = await client.get_characteristic_iid(char)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/bleak.py", line 58, in get_characteristic_iid
    value = bytes(await self.read_gatt_descriptor(iid_handle.handle))
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 609, in read_gatt_descriptor
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Not connected

```

**Comment by bdraco** [comment]
We do clear them, we just need to do it under the lock.  `self.close(clear_cached_services=True)`

```
    def _async_ble_device_update(self, device: BLEDevice) -> None:
        """Update the BLE device."""
        if self.device and ble_device_has_changed(self.device, device):
            self._cached_services = None
            logger.debug(
                "BLE address changed from %s to %s; closing connection",
                self.device.address,
                device.address,
            )
            async_create_task(self.close())
        self.device = device
```
