### ISSUE TITLE
Sometimes service resolution fails on the edge of bluetooth range

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#161]
We need to disconnect and reconnect in this case
```
Logger: homeassistant.config_entries
Source: components/homekit_controller/connection.py:204
First occurred: 2:11:29 PM (1 occurrences)
Last logged: 2:11:29 PM

Error setting up entry VOCOlinc-VS1-1857C6 for homekit_controller
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/__init__.py", line 42, in async_setup_entry
    await conn.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 204, in async_setup
    await self.pairing.async_populate_accessories_state(force_update=True)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 596, in async_populate_accessories_state
    await self._async_populate_accessories_state(force_update)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 103, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 66, in _async_wrap
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 608, in _async_populate_accessories_state
    await self._populate_accessories_and_characteristics(force_update)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 642, in _populate_accessories_and_characteristics
    await self._async_pair_verify()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 410, in _async_pair_verify
    session_id, derive = await drive_pairing_state_machine(
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 288, in drive_pairing_state_machine
    char = client.get_characteristic(ServicesTypes.PAIRING, characteristic)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/bleak.py", line 37, in get_characteristic
    raise ValueError(
ValueError: Service 00000055-0000-1000-8000-0026BB765291 not found, available services: []
```

**Comment by bdraco** [comment]
Once this happens, I can reload the config entry and it will reconnect and work but it never goes unavailable

**Comment by bdraco** [comment]
This was a race in bleak that has since been fixed
