### ISSUE TITLE
Handle EOFError

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#169]
```
Logger: homeassistant.config_entries
Source: components/homekit_controller/connection.py:198
First occurred: 8:53:38 PM (1 occurrences)
Last logged: 8:53:38 PM

Error setting up entry VOCOlinc-VS1-185620 for homekit_controller
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/__init__.py", line 41, in async_setup_entry
    await conn.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 198, in async_setup
    await self.pairing.async_populate_accessories_state(force_update=True)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 564, in async_populate_accessories_state
    await self._async_populate_accessories_state(force_update)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 111, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 75, in _async_wrap
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 576, in _async_populate_accessories_state
    await self._populate_accessories_and_characteristics(force_update)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 607, in _populate_accessories_and_characteristics
    await self._async_pair_verify()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 387, in _async_pair_verify
    session_id, derive = await drive_pairing_state_machine(
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 257, in drive_pairing_state_machine
    decoded = await _pairing_char_write(client, char, iid, request)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 211, in _pairing_char_write
    data = await char_write(client, None, None, handle, iid, next_write)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 194, in char_write
    pdu_status, data = await ble_request(
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 99, in ble_request
    await _write_pdu(client, encryption_key, opcode, handle, iid, data, tid)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 126, in _write_pdu
    await client.write_gatt_char(handle, write, True)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 695, in write_gatt_char
    reply = await self._bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 337, in call
    await future
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 404, in _message_reader
    if self._unmarshaller.unmarshall():
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/_private/unmarshaller.py", line 332, in unmarshall
    self._read_header()
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/_private/unmarshaller.py", line 271, in _read_header
    self.read_to_offset(HEADER_SIGNATURE_SIZE)
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/_private/unmarshaller.py", line 174, in read_to_offset
    raise EOFError()
EOFError
```

**Comment by bdraco** [comment]
https://github.com/hbldh/bleak/issues/409

**Comment by bdraco** [comment]
This is already handled in led-ble and yalexs-ble and bluetooth-adapters but forgot to do it switchobot and aiohomekit
