### ISSUE TITLE
Calls to `zeroconf.get_service_info` need to be wrapped with try/except for `zeroconf.BadTypeInNameException` or `zeroconf.Error`

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#17]
I'm working on fixing this for Home Assistant's browser when I noticed `aiohomekit` is affected as well

```
2020-08-13 18:33:40 ERROR (zeroconf-ServiceBrowser__hap._tcp.local._1206) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1680, in run
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1438, in fire
    h(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1536, in on_change
    listener.add_service(*args)
  File "/usr/local/lib/python3.8/site-packages/aiohomekit/zeroconf/__init__.py", line 59, in add_service
    info = zeroconf.get_service_info(zeroconf_type, name)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2371, in get_service_info
    info = ServiceInfo(type_, name)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1732, in __init__
    if not type_.endswith(service_type_name(name, allow_underscores=True)):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 268, in service_type_name
    raise BadTypeInNameException("Type '%s' must end with '._tcp.local.' or '._udp.local.'" % type_)
zeroconf.BadTypeInNameException: Type 'crash.local.' must end with '._tcp.local.' or '._udp.local.'
```

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/38851

**Comment by Jc2k** [comment]
Will try and find some time to look at this (and the other draft PR we have oustanding) as soon as I can.

Do we know if there are any "real" HAP devices that are affected by this, and this strict check renders them undiscoverable?

**Comment by bdraco** [comment]
> Will try and find some time to look at this (and the other draft PR we have oustanding) as soon as I can.
> 
> Do we know if there are any "real" HAP devices that are affected by this, and this strict check renders them undiscoverable?

Yes, this is a real world example of an iHome SmartMonitor that causes this issue which in turns break all the devices on the network since they can't be found. 

There are unsolved issue on the Home Assistant side where the cause was never found until now

https://github.com/home-assistant/core/issues/36201
https://github.com/home-assistant/core/issues/33085
https://github.com/home-assistant/core/issues/31262
https://github.com/home-assistant/core/issues/2787

**Comment by Jc2k** [comment]
What I was really trying to ask is if we add a workaround like catching those exceptions, will that leave the "broken" device itself undetected? Or are the _hap records themselves valid?

I've already raised a ticket upstream where their validation was too strict. Parsing should probably be very forgiving of crappy implementations?

**Comment by Jc2k** [comment]
(I think it's the reason for some open homekit_controller discovery issues btw)

**Comment by bdraco** [comment]
![Image](https://user-images.githubusercontent.com/663432/90198792-5d66b100-dd98-11ea-9e28-16b570b4c588.jpg)
@dmulcahey provided the device


You can replicate but commenting out all the `raise`s for the `zeroconf.BadTypeInNameException` and running the registration example with the following patch.
```
diff --git a/examples/registration.py b/examples/registration.py
index 65c2219..8c2f2f1 100755
--- a/examples/registration.py
+++ b/examples/registration.py
@@ -31,8 +31,8 @@ if __name__ == '__main__':
     desc = {'path': '/~paulsm/'}
 
     info = ServiceInfo(
-        "_http._tcp.local.",
-        "Paul's Test Web Site._http._tcp.local.",
+        "_hap._tcp.local.",
+        "crash.local.",
         addresses=[socket.inet_aton("127.0.0.1")],
         port=80,
         properties=desc,
```

**Comment by Jc2k** [comment]
This should be patched in `main`. Seems to work, but would be great if you could check it out on your end too.

**Comment by bdraco** [comment]
Working as expected 👍 🥇 

```
2020-08-14 14:22:36 ERROR (zeroconf-ServiceBrowser__elg._tcp.local.-_viziocast._tcp.local.-_printer._tcp.local.-_axis-video._tcp.local.-_daap._tcp.local.-_spotify-connect._tcp.local.-_api._udp.local.-_bond._tcp.local.-_dkapi._tcp.local.-_ssh._tcp.local.-_nut._tcp.local.-_googlecast._tcp.local.-_esphomelib._tcp.local.-_hap._tcp.local.-_wled._tcp.local.-_ipps._tcp.local.-_miio._udp.local.-_ipp._tcp.local.-_plugwise._tcp.local.-_Volumio._tcp.local._296) [homeassistant.components.zeroconf] Failed to get info for device crash.local.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 217, in service_update
    service_info = zeroconf.get_service_info(service_type, name)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2371, in get_service_info
    info = ServiceInfo(type_, name)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1732, in __init__
    if not type_.endswith(service_type_name(name, allow_underscores=True)):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 268, in service_type_name
    raise BadTypeInNameException("Type '%s' must end with '._tcp.local.' or '._udp.local.'" % type_)
zeroconf.BadTypeInNameException: Type 'crash.local.' must end with '._tcp.local.' or '._udp.local.'
2020-08-14 14:22:48 WARNING (zeroconf-ServiceBrowser__hap._tcp.local._302) [aiohomekit.zeroconf] Cannot finish discovering crash.local. as it has an invalid discovery record
```

**Comment by bdraco** [comment]
I was now able to pair with another valid device while the affected fake device was on the network.

**Comment by Jc2k** [comment]
Lovely :-) I've pushed a tag - if tests pass it should update a wheel in a few minutes for 0.2.47. If you don't beat me to the punch i'll try and submit a PR against HA this weekend. Got a few "meat space" things that need doing first though.
