### ISSUE TITLE
Retry getting disconnected events

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#187]
We currently call `get_characteristics_without_retry` for disconnected events to ensure we don't hold the transaction lock for too long when there are multiple bumps of the GSN.  Instead we can do a call later + cancel strategy to debounce the update a bit so we can retry.

https://github.com/Jc2k/aiohomekit/blob/4d05322338af3d3df81796cd7209c3e28a707987/aiohomekit/controller/ble/pairing.py#L327

Borrow some of the ideas from
https://github.com/bdraco/yalexs-ble/blob/2bfa166a00e2d64a9bf14ff2f127c8042e92b386/src/yalexs_ble/push.py#L523

**Comment by bdraco** [comment]
```
2022-10-24 10:17:51.585 DEBUG (MainThread) [bleak_retry_connector] VOCOlinc-VS1-185620 [E5:AB:B3:23:65:23] (id=E4:2F:25:E5:71:C5) - E5:AB:B3:23:65:23: Timed out trying to connect (attempt: 5, last rssi: -66)
2022-10-24 10:17:51.585 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] VOCOlinc-VS1-185620 [E5:AB:B3:23:65:23] (id=E4:2F:25:E5:71:C5): Client not connected; rssi=-66
2022-10-24 10:17:51.585 ERROR (MainThread) [aiohomekit.controller.ble.pairing] VOCOlinc-VS1-185620 [E5:AB:B3:23:65:23] (id=E4:2F:25:E5:71:C5): Failed to fetch disconnected events: VOCOlinc-VS1-185620 [E5:AB:B3:23:65:23] (id=E4:2F:25:E5:71:C5) is not connected; rssi=-66
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 470, in _process_disconnected_events
    protocol_param = await self.get_all_protocol_params()
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 144, in _async_operation_lock_wrap
    return await func(self, *args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 600, in _async_wrap_bluetooth_connection_error_retry
    return await func(*args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 765, in get_all_protocol_params
    return await self._get_all_protocol_params()
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 774, in _get_all_protocol_params
    resp = await self._async_request(
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 308, in _async_request
    return await self._async_request_under_lock(opcode, char, data, iid)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 320, in _async_request_under_lock
    raise AccessoryDisconnectedError(f"{self.name} is not connected")
aiohomekit.exceptions.AccessoryDisconnectedError: VOCOlinc-VS1-185620 [E5:AB:B3:23:65:23] (id=E4:2F:25:E5:71:C5) is not connected
```

**Comment by bdraco** [comment]
Went to fix this and realized `_process_disconnected_events` is now calling two function that are both wrapped for retry so this is already done
