### ISSUE TITLE
Pairing fails with wemo smart scene controller

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#194]
```
Oct 18 16:51:44 homeassistant homeassistant[482]: 2022-10-18 11:51:44.074 DEBUG (MainThread) [bleak_retry_connector] Bleak error calling <function BlePairing._async_populate_accessories_state at 0xffff66312560>, backing off: 0.1, retrying...
Oct 18 16:51:44 homeassistant homeassistant[482]: Traceback (most recent call last):
Oct 18 16:51:44 homeassistant homeassistant[482]:   File "/usr/local/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 600, in _async_wrap_bluetooth_connection_error_retry
Oct 18 16:51:44 homeassistant homeassistant[482]:     return await func(*args, **kwargs)
Oct 18 16:51:44 homeassistant homeassistant[482]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 555, in _async_populate_accessories_state
Oct 18 16:51:44 homeassistant homeassistant[482]:     await self._populate_accessories_and_characteristics(force_update)
Oct 18 16:51:44 homeassistant homeassistant[482]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 589, in _populate_accessories_and_characteristics
Oct 18 16:51:44 homeassistant homeassistant[482]:     await self._populate_char_values(config_changed)
Oct 18 16:51:44 homeassistant homeassistant[482]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 522, in _populate_char_values
Oct 18 16:51:44 homeassistant homeassistant[482]:     results = await self._get_characteristics_while_connected(chars)
Oct 18 16:51:44 homeassistant homeassistant[482]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 726, in _get_characteristics_while_connected
Oct 18 16:51:44 homeassistant homeassistant[482]:     data = await self._async_request_under_lock(OpCode.CHAR_READ, char)
Oct 18 16:51:44 homeassistant homeassistant[482]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 254, in _async_request_under_lock
Oct 18 16:51:44 homeassistant homeassistant[482]:     endpoint = self.client.get_characteristic(char.service.type, char.type)
Oct 18 16:51:44 homeassistant homeassistant[482]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/bleak.py", line 85, in get_characteristic
Oct 18 16:51:44 homeassistant homeassistant[482]:     service = self.services.get_service(service_type)
Oct 18 16:51:44 homeassistant homeassistant[482]:   File "/usr/local/lib/python3.10/site-packages/bleak/backends/service.py", line 158, in get_service
Oct 18 16:51:44 homeassistant homeassistant[482]:     raise BleakError(
Oct 18 16:51:44 homeassistant homeassistant[482]: bleak.exc.BleakError: Multiple Services with this UUID, refer to your desired service by the `handle` attribute instead.
```

**Comment by bdraco** [comment]
```
INFO:__main__:Connected: True
INFO:__main__:[Service] 00000129-0000-1000-8000-0026bb765291 (Handle: 146): Unknown
ERROR:__main__:	[Characteristic] 000000a5-0000-1000-8000-0026bb765291 (Handle: 149): Unknown (read,write), Value: Multiple Characteristics with this UUID, refer to your desired characteristic by the `handle` attribute instead.
INFO:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 151): None) | Value: b'\xf1\x00'
ERROR:__main__:	[Characteristic] 00000131-0000-1000-8000-0026bb765291 (Handle: 155): Unknown (read,write), Value: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 157): None) | Value: Not connected
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 147): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 00000130-0000-1000-8000-0026bb765291 (Handle: 152): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 154): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000139-0000-1000-8000-0026bb765291 (Handle: 164): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 166): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 167): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000037-0000-1000-8000-0026bb765291 (Handle: 158): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 160): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000138-0000-1000-8000-0026bb765291 (Handle: 161): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 163): None) | Value: Not connected
INFO:__main__:[Service] 00000236-0000-1000-8000-0026bb765291 (Handle: 132): Unknown
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 133): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 00000234-0000-1000-8000-0026bb765291 (Handle: 138): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 141): None) | Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 140): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000235-0000-1000-8000-0026bb765291 (Handle: 142): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 144): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 145): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 000000a5-0000-1000-8000-0026bb765291 (Handle: 135): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 137): None) | Value: Not connected
INFO:__main__:[Service] 000000cc-0000-1000-8000-0026bb765291 (Handle: 61): Unknown
ERROR:__main__:	[Characteristic] 000000a5-0000-1000-8000-0026bb765291 (Handle: 64): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 66): None) | Value: Not connected
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 62): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 000000cd-0000-1000-8000-0026bb765291 (Handle: 67): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 69): None) | Value: Not connected
INFO:__main__:[Service] 00000055-0000-1000-8000-0026bb765291 (Handle: 46): Unknown
ERROR:__main__:	[Characteristic] 0000004c-0000-1000-8000-0026bb765291 (Handle: 49): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 51): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000050-0000-1000-8000-0026bb765291 (Handle: 58): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 60): None) | Value: Not connected
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 47): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 0000004e-0000-1000-8000-0026bb765291 (Handle: 52): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 54): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 0000004f-0000-1000-8000-0026bb765291 (Handle: 55): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 57): None) | Value: Not connected
INFO:__main__:[Service] 00000089-0000-1000-8000-0026bb765291 (Handle: 70): Unknown
ERROR:__main__:	[Characteristic] 000000a5-0000-1000-8000-0026bb765291 (Handle: 73): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 75): None) | Value: Not connected
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 71): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 00000073-0000-1000-8000-0026bb765291 (Handle: 79): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 81): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 82): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000023-0000-1000-8000-0026bb765291 (Handle: 76): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 78): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 000000cb-0000-1000-8000-0026bb765291 (Handle: 83): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 85): None) | Value: Not connected
INFO:__main__:[Service] 00000089-0000-1000-8000-0026bb765291 (Handle: 102): Unknown
ERROR:__main__:	[Characteristic] 00000073-0000-1000-8000-0026bb765291 (Handle: 111): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 113): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 114): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000023-0000-1000-8000-0026bb765291 (Handle: 108): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 110): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 000000cb-0000-1000-8000-0026bb765291 (Handle: 115): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 117): None) | Value: Not connected
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 103): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 000000a5-0000-1000-8000-0026bb765291 (Handle: 105): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 107): None) | Value: Not connected
INFO:__main__:[Service] 00000089-0000-1000-8000-0026bb765291 (Handle: 86): Unknown
ERROR:__main__:	[Characteristic] 000000cb-0000-1000-8000-0026bb765291 (Handle: 99): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 101): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 000000a5-0000-1000-8000-0026bb765291 (Handle: 89): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 91): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000073-0000-1000-8000-0026bb765291 (Handle: 95): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 97): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 98): None) | Value: Not connected
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 87): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 00000023-0000-1000-8000-0026bb765291 (Handle: 92): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 94): None) | Value: Not connected
INFO:__main__:[Service] 000000a2-0000-1000-8000-0026bb765291 (Handle: 37): Unknown
ERROR:__main__:	[Characteristic] 00000037-0000-1000-8000-0026bb765291 (Handle: 43): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 45): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 000000a5-0000-1000-8000-0026bb765291 (Handle: 40): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 42): None) | Value: Not connected
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 38): Unknown (read), Value: Not connected
INFO:__main__:[Service] 0000003e-0000-1000-8000-0026bb765291 (Handle: 6): Unknown
ERROR:__main__:	[Characteristic] 00000053-0000-1000-8000-0026bb765291 (Handle: 28): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 30): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 34ab8811-ac7f-4340-bac3-fd6a85f9943b (Handle: 31): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 33): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000052-0000-1000-8000-0026bb765291 (Handle: 24): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 26): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 27): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000014-0000-1000-8000-0026bb765291 (Handle: 9): Hardcopy Data Channel (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 11): None) | Value: Not connected
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 7): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 00000220-0000-1000-8000-0026bb765291 (Handle: 34): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 36): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000020-0000-1000-8000-0026bb765291 (Handle: 12): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 14): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000023-0000-1000-8000-0026bb765291 (Handle: 18): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 20): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000030-0000-1000-8000-0026bb765291 (Handle: 21): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 23): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000021-0000-1000-8000-0026bb765291 (Handle: 15): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 17): None) | Value: Not connected
INFO:__main__:[Service] 00000096-0000-1000-8000-0026bb765291 (Handle: 118): Unknown
ERROR:__main__:	[Characteristic] e604e95d-a759-4817-87d3-aa005083a0d1 (Handle: 119): Unknown (read), Value: Not connected
ERROR:__main__:	[Characteristic] 00000068-0000-1000-8000-0026bb765291 (Handle: 121): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 124): None) | Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 123): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000079-0000-1000-8000-0026bb765291 (Handle: 125): Unknown (read,write,indicate), Value: Not connected
ERROR:__main__:		[Descriptor] 00002902-0000-1000-8000-00805f9b34fb (Handle: 127): Client Characteristic Configuration) | Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 128): None) | Value: Not connected
ERROR:__main__:	[Characteristic] 00000023-0000-1000-8000-0026bb765291 (Handle: 129): Unknown (read,write), Value: Not connected
ERROR:__main__:		[Descriptor] dc46f0fe-81d2-4616-b5d9-6abdd796939a (Handle: 131): None) | Value: Not connected
```
