### ISSUE TITLE
Clear services cache when pairing fails

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#205]
```
Oct 24 14:05:32 homeassistant homeassistant[483]: 2022-10-24 09:05:32.237 DEBUG (MainThread) [aiohomekit.controller.ble.discovery] Eve Room 0881 (EF:69:05:18:C5:37): Ensure connected with device EF:69:05:18:C5:37: Eve Room 0881; rssi=-64
Oct 24 14:05:32 homeassistant homeassistant[483]: 2022-10-24 09:05:32.237 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Oct 24 14:05:32 homeassistant homeassistant[483]: Traceback (most recent call last):
Oct 24 14:05:32 homeassistant homeassistant[483]:   File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 479, in async_step_pair
Oct 24 14:05:32 homeassistant homeassistant[483]:     self.finish_pairing = await discovery.async_start_pairing(self.hkid)
Oct 24 14:05:32 homeassistant homeassistant[483]:   File "/usr/local/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 600, in _async_wrap_bluetooth_connection_error_retry
Oct 24 14:05:32 homeassistant homeassistant[483]:     return await func(*args, **kwargs)
Oct 24 14:05:32 homeassistant homeassistant[483]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/discovery.py", line 138, in async_start_pairing
Oct 24 14:05:32 homeassistant homeassistant[483]:     salt, pub_key = await self._async_start_pairing(alias)
Oct 24 14:05:32 homeassistant homeassistant[483]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/discovery.py", line 120, in _async_start_pairing
Oct 24 14:05:32 homeassistant homeassistant[483]:     ff_char = self.client.get_characteristic(
Oct 24 14:05:32 homeassistant homeassistant[483]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/bleak.py", line 94, in get_characteristic
Oct 24 14:05:32 homeassistant homeassistant[483]:     raise ValueError(
Oct 24 14:05:32 homeassistant homeassistant[483]: ValueError: Service 00000055-0000-1000-8000-0026BB765291 not found, available services: []
```

**Comment by bdraco** [comment]
found this will testing with an eve room 1 trying to replicate https://github.com/home-assistant/core/issues/80177
