### ISSUE TITLE
When attempting to close a garage door with an obstruction status code 70408 is thrown

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#22]
I think this is a bug in the `myq` homekit bridge as I believe these are supposed to be negative.

```
2020-10-22 22:22:21 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall cover.close_cover (c:da4a8e04b5257836ff910b3f366b1beb): entity_id=['cover.large_garage_door_local']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1465, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1484, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/cover.py", line 105, in async_close_cover
    await self.set_door_state(STATE_CLOSED)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/cover.py", line 109, in set_door_state
    await self.async_put_characteristics(
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/__init__.py", line 94, in async_put_characteristics
    return await self._accessory.put_characteristics(payload)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 403, in put_characteristics
    results = await self.pairing.put_characteristics(characteristics)
  File "/usr/local/lib/python3.8/site-packages/aiohomekit/controller/ip/pairing.py", line 265, in put_characteristics
    data = {
  File "/usr/local/lib/python3.8/site-packages/aiohomekit/controller/ip/pairing.py", line 268, in <dictcomp>
    "description": HapStatusCodes[d["status"]],
  File "/usr/local/lib/python3.8/site-packages/aiohomekit/protocol/statuscodes.py", line 58, in __getitem__
    raise KeyError(f"Item {item} not found")
KeyError: 'Item 70408 not found'
```

**Comment by Jc2k** [comment]
I've seen this before - probably the same brand of garage door opener - even though off spec i was going to change the error handler to invert positive error codes before trying but haven't got round to it yet.

**Comment by mikewesner** [comment]
Just wanted to update this with another similar stack.   Using the 819LMB bridge with a few liftmaster myq garage doors.  

`2021-01-17 10:55:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 252, in async_process_entity_map
await self.async_update()
File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 379, in async_update
new_values_dict = await self.get_characteristics(
File "/usr/src/homeassistant/homeassistant/components/homekit_controller/connection.py", line 415, in get_characteristics
return await self.pairing.get_characteristics(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/aiohomekit/controller/ip/pairing.py", line 236, in get_characteristics
return format_characteristic_list(response)
File "/usr/local/lib/python3.8/site-packages/aiohomekit/controller/ip/pairing.py", line 53, in format_characteristic_list
c["description"] = HapStatusCodes[c["status"]]
File "/usr/local/lib/python3.8/site-packages/aiohomekit/protocol/statuscodes.py", line 58, in __getitem__
raise KeyError(f"Item {item} not found")
KeyError: 'Item 70402 not found'`

**Comment by mikewesner** [comment]
Please let me know if I can help test something or gather more info on this.  Happy to help how I can.

**Comment by Jc2k** [comment]
Just to be clear - right now the only fix planned for this is to work around their broken HAP implementation enough so we can at least know the correct error message the device is sending. In the context of HA this will eventually manifest as a "Unavailable" state in the frontend. Because that's a cosmetic fix it's currently low down my list.

There is no planned fix that will make it work, and i'm not sure there is anything we could do on that front. I.e. If their HAP implementation was correct `70402` should actually be `-70402`, which is a `StatusServiceCommunicationFailure` or `HAPSTATUSCODE_SERVICE_OFFLINE` in other HAP libraries. I suspect this is a device failure of some kind, likely a communication error between the bridge and doors.

**Comment by mikewesner** [comment]
Interesting.  Thanks!  That makes sense.  The doors do function and this is probably just tiny bit flakey.  I haven't dug into it to figure out if it is doing retries or how it handles any of this.  For the most part the status of the doors seems correct and it responds quickly.

**Comment by bdraco** [comment]
Since they are all supposed to be negative we can probably abs the value for compat

**Comment by Jc2k** [comment]
Thats the plan I just haven't done it yet. Want to actually do something based on these error codes on the HA side too. Right now they would just be dropped.
