### ISSUE TITLE
Don't raise an exception on subscribe to gatt notify if the accessory disconnects as it wants disconnected events

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#224]
```
2022-10-30 15:15:29.422 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] VOCOlinc-VS1-185620 [CB:86:15:F3:0A:14] (id=C0:3E:A4:C9:D1:46): Subscribing to gatt notify for iid: 93
2022-10-30 15:15:29.425 DEBUG (MainThread) [aiohomekit.controller.ble.client] Queuing fragment for write: b'\x00\x08y\x07\x00\x02\x00\x02\x00'
2022-10-30 15:15:29.600 DEBUG (MainThread) [homeassistant.components.esphome.bluetooth.client] Connection state changed: connected=False mtu=158 error=19
2022-10-30 15:15:29.600 DEBUG (MainThread) [homeassistant.components.esphome.bluetooth.client] tracker_proxy_b: BLE device disconnected
2022-10-30 15:15:29.603 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] VOCOlinc-VS1-185620 [CB:86:15:F3:0A:14] (id=C0:3E:A4:C9:D1:46): Session closed callback: rssi=-64
2022-10-30 15:15:29.605 DEBUG (MainThread) [bleak_retry_connector] Bleak error calling <function BlePairing._async_populate_accessories_state at 0x1621c0e50>, backing off: 0.1, retrying...
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 620, in _async_wrap_bluetooth_connection_error_retry
    return await func(*args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 915, in _async_populate_accessories_state
    await self._async_restore_subscriptions()
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 1054, in _async_restore_subscriptions
    protocol_param = await self._get_all_protocol_params()
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 858, in _get_all_protocol_params
    resp = await self._async_request(
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 326, in _async_request
    return await self._async_request_under_lock(opcode, char, data, iid)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 345, in _async_request_under_lock
    pdu_status, result_data = await ble_request(
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 73, in ble_request
    return await _read_pdu(client, decryption_key, handle, tid)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 109, in _read_pdu
    data = await client.read_gatt_char(handle)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/bleak/__init__.py", line 571, in read_gatt_char
    return await self._backend.read_gatt_char(char_specifier, **kwargs)
  File "/Users/bdraco/home-assistant/homeassistant/components/esphome/bluetooth/client.py", line 63, in _async_wrap_bluetooth_connected_operation
    raise BleakError(
bleak.exc.BleakError: VOCOlinc-VS1-185620 (CB:86:15:F3:0A:14): Disconnected during operation
2022-10-30 15:15:29.606 DEBUG (MainThread) [homeassistant.components.esphome.entry_data] tracker_proxy_b: BLE connection limits: 1/1
2022-10-30 15:15:29.708 DEBUG (MainThread) [bleak_retry_connector] VOCOlinc-VS1-185620 [CB:86:15:F3:0A:14] (id=C0:3E:A4:C9:D1:46) - CB:86:15:F3:0A:14: Connecting (attempt: 1, last rssi: -64)
2022-10-30 15:15:29.708 DEBUG (MainThread) [homeassistant.components.esphome.bluetooth] Checking if tracker_proxy_b can connect, available=True, ble_connections_free=1
2022-10-30 15:15:29.718 DEBUG (MainThread) [homeassistant.components.esphome.entry_data] tracker_proxy_b: BLE connection limits: 0/1
```

**Comment by bdraco** [comment]
We need to do all our gatt notify requests at the very end of the operation since asking for one can result in the accessory deciding that its good to disconnect now and you can have disconnected / broadcast events instead

**Comment by bdraco** [comment]
This one is harder to fix because we can subscribe to them in batches during startup
