### ISSUE TITLE
Accessories that do not send normal advertisements after subscribing to notify need the ability to restore the GSN between restarts

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#225]
```
Oct 30 21:16:54 homeassistant homeassistant[468]: Traceback (most recent call last):
Oct 30 21:16:54 homeassistant homeassistant[468]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 506, in _process_disconnected_events
Oct 30 21:16:54 homeassistant homeassistant[468]:     protocol_param = await self._process_disconnected_events_with_retry()
Oct 30 21:16:54 homeassistant homeassistant[468]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 154, in _async_operation_lock_wrap
Oct 30 21:16:54 homeassistant homeassistant[468]:     return await func(self, *args, **kwargs)
Oct 30 21:16:54 homeassistant homeassistant[468]:   File "/usr/local/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 619, in _async_wrap_bluetooth_connection_error_retry
Oct 30 21:16:54 homeassistant homeassistant[468]:     return await func(*args, **kwargs)
Oct 30 21:16:54 homeassistant homeassistant[468]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 168, in _async_restore_and_resume
Oct 30 21:16:54 homeassistant homeassistant[468]:     await self._populate_accessories_and_characteristics()
Oct 30 21:16:54 homeassistant homeassistant[468]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 945, in _populate_accessories_and_characteristics
Oct 30 21:16:54 homeassistant homeassistant[468]:     made_connection = await self._ensure_connected(attempts)
Oct 30 21:16:54 homeassistant homeassistant[468]:   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 401, in _ensure_connected
Oct 30 21:16:54 homeassistant homeassistant[468]:     raise AccessoryNotFoundError(
Oct 30 21:16:54 homeassistant homeassistant[468]: aiohomekit.exceptions.AccessoryNotFoundError: [D0:72:0E:4B:7F:6C] (id=42:15:4C:F4:B9:DE): Could not find D0:72:0E:4B:7F:6C

```

Not sure sure how to handle this one as all the logic requires this.

**Comment by bdraco** [comment]
To solve this we need to store the GSN and restore the description from cache

**Comment by bdraco** [comment]
```
Oct 30 22:48:50 homeassistant homeassistant[468]: 2022-10-30 17:48:50.080 ERROR (MainThread) [aiohomekit.controller.ble.pairing] [D0:72:0E:4B:7F:6C] (id=42:15:4C:F4:B9:DE): Received encrypted notification before advertisement.
Oct 30 22:48:56 homeassistant homeassistant[468]: 2022-10-30 17:48:56.847 ERROR (MainThread) [aiohomekit.controller.ble.pairing] [D0:72:0E:4B:7F:6C] (id=42:15:4C:F4:B9:DE): Received encrypted notification before advertisement.

Oct 30 22:49:07 homeassistant homeassistant[468]: 2022-10-30 17:49:07.327 ERROR (MainThread) [aiohomekit.controller.ble.pairing] [D0:72:0E:4B:7F:6C] (id=42:15:4C:F4:B9:DE): Received encrypted notification before advertisement.
Oct 30 22:49:08 homeassistant homeassistant[468]: 2022-10-30 17:49:08.781 ERROR (MainThread) [aiohomekit.controller.ble.pairing] [D0:72:0E:4B:7F:6C] (id=42:15:4C:F4:B9:DE): Received encrypted notification before advertisement.
Oct 30 22:49:13 homeassistant homeassistant[468]: 2022-10-30 17:49:13.344 ERROR (MainThread) [aiohomekit.controller.ble.pairing] [D0:72:0E:4B:7F:6C] (id=42:15:4C:F4:B9:DE): Received encrypted notification before advertisement.
Oct 30 22:49:13 homeassistant homeassistant[468]: 2022-10-30 17:49:13.735 ERROR (MainThread) [aiohomekit.controller.ble.pairing] [D0:72:0E:4B:7F:6C] (id=42:15:4C:F4:B9:DE): Received encrypted notification before advertisement.

```

**Comment by bdraco** [comment]
Was Wemo stage doesn't send out normal advertisements frequently

**Comment by bdraco** [comment]
Ideally we check the GSN at startup to see if its the same as the one we had when we restarted since we avoid the connect at startup if it hasn't changed
