### ISSUE TITLE
Using aiohomekit standalone: transport not supported

### ISSUE THREAD

**Issue by voltagex** [Jc2k/aiohomekit#280]
Yes, I know this is really only for Home Assistant, but I am trying to see if there is an issue in Home Assistant or somewhere else

```
import aiohomekit
from zeroconf import asyncio as az
import asyncio
async def go():
    z = az.AsyncZeroconf()
    c = aiohomekit.Controller(z)

    await c.async_start()
    async for d in c.async_discover():
        print(d)


if __name__ == '__main__':
    asyncio.run(go())
```

```
Traceback (most recent call last):
  File "C:\git\test-homekit\stuff.py", line 14, in <module>
    asyncio.run(go())
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\git\test-homekit\stuff.py", line 8, in go
    await c.async_start()
  File "C:\git\test-homekit\env\lib\site-packages\aiohomekit\controller\controller.py", line 83, in async_start
    await self._async_register_backend(
  File "C:\git\test-homekit\env\lib\site-packages\aiohomekit\controller\controller.py", line 75, in _async_register_backend
    self._transports.append(await self._tasks.enter_async_context(controller))
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 619, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "C:\git\test-homekit\env\lib\site-packages\aiohomekit\controller\abstract.py", line 437, in __aenter__
    await self.async_start()
  File "C:\git\test-homekit\env\lib\site-packages\aiohomekit\zeroconf.py", line 223, in async_start
    self._browser = find_brower_for_hap_type(
  File "C:\git\test-homekit\env\lib\site-packages\aiohomekit\zeroconf.py", line 148, in find_brower_for_hap_type
    raise TransportNotSupportedError(f"There is no zeroconf browser for {hap_type}")
aiohomekit.exceptions.TransportNotSupportedError: Transport There is no zeroconf browser for _hap._tcp.local. not supported. See setup.py for required dependencies.
```

https://github.com/Jc2k/aiohomekit/blob/db950276374b73034618c6a2e1225f9d67ba6732/aiohomekit/exceptions.py#L293

There's no `setup.py` in this project any more (?) but I am assuming this means I'm missing some Zeroconf support on Windows? Theoretically Windows 10 should support Zeroconf properly now, and I probably also have Bonjour installed.

**Comment by Jc2k** [comment]
You have to configure zeroconf manually with the right service browsers, like the cli does. This is left to the API user become home assistant already configured the browsers itself and it would be bad to configure them twice. If you are just trying to debug HA, using the "aiohomekitctl discover" cli.

setup.py is somewhat deprecated in python, and for many projects pyproject.toml fully or partially replaces it.

Zeroconf in HA is implemented in pure python, it should not depend on bonjour or other operating system services.

**Comment by voltagex** [comment]
TIL `aiohomekitctl`, thanks. I am not entirely sure what that error should be, I think it needs to be changed in `exceptions.py` to read something along the lines of `Transport error: {t}` to be clearer.
