### ISSUE TITLE
Eve Degree: Various BLE errors

### ISSUE THREAD

**Issue by Jc2k** [Jc2k/aiohomekit#283]
Eve Degree 1.0, Firmware 1.2.8. macOS Ventura, python 3.10.

HA dev, latest tag of aiohomekit.

Pairing works and is pretty fast. Then I restarted HA and pretty much immediately got:

```
2023-02-07 07:30:58.276 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/john/Projects/home-assistant/homeassistant/components/homekit_controller/connection.py", line 194, in _async_populate_ble_accessory_state
    await self.pairing.async_populate_accessories_state(force_update=True)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 1048, in async_populate_accessories_state
    await self._async_populate_accessories_state(force_update, attempts)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 188, in _async_operation_lock_wrap
    return await func(self, *args, **kwargs)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 447, in _async_wrap_bluetooth_connection_error_retry
    return await func(*args, **kwargs)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 204, in _async_disconnect_on_missing_services_wrap
    return await func(self, *args, **kwargs)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 1061, in _async_populate_accessories_state
    await self._populate_accessories_and_characteristics(force_update, attempts)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 1132, in _populate_accessories_and_characteristics
    await self._async_pair_verify()
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 572, in _async_pair_verify
    session_id, derive = await drive_pairing_state_machine(
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 233, in drive_pairing_state_machine
    request, expected = state_machine.send(decoded)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 492, in get_session_keys
    raise InvalidError("M2: Missing public key")
aiohomekit.exceptions.InvalidError: M2: Missing public key
```

And then shortly after:

```
2023-02-07 07:32:02.506 ERROR (MainThread) [aiohomekit.utils] Failure running background task: Task-1382
Traceback (most recent call last):
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/utils.py", line 35, in _handle_task_result
    task.result()
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 609, in _process_disconnected_events
    protocol_param = await self._process_disconnected_events_with_retry()
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 188, in _async_operation_lock_wrap
    return await func(self, *args, **kwargs)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 447, in _async_wrap_bluetooth_connection_error_retry
    return await func(*args, **kwargs)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 204, in _async_disconnect_on_missing_services_wrap
    return await func(self, *args, **kwargs)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 228, in _async_restore_and_resume
    await self._populate_accessories_and_characteristics()
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 1132, in _populate_accessories_and_characteristics
    await self._async_pair_verify()
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 572, in _async_pair_verify
    session_id, derive = await drive_pairing_state_machine(
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 232, in drive_pairing_state_machine
    decoded = await _pairing_char_write(client, char, iid, request)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 186, in _pairing_char_write
    data = await char_write(client, None, None, handle, iid, next_write)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 169, in char_write
    pdu_status, data = await ble_request(
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 73, in ble_request
    return await _read_pdu(client, decryption_key, handle, tid)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 120, in _read_pdu
    status, expected_length, data = decode_pdu(tid, data)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/pdu.py", line 112, in decode_pdu
    raise ValueError(
ValueError: Expected transaction 118 but got transaction 38
```

**Comment by codyc1515** [comment]
I have that device paired fine, albeit it does not seem to push updates. It has to be polled after a while which I do by reloading the integration on a scheduled automation.

```
Eve Degree
20EAF9901
by Elgato
Firmware: 1.2.8
Hardware: 1.0.0
```
