### ISSUE TITLE
Out of order pairing steps when using HomeSpan (async race condition?)

### ISSUE THREAD

**Issue by phybros** [Jc2k/aiohomekit#343]
HomeSpan is a library for ESP32 devices to enable them to speak HomeKit. After a huge amount of tests, it seems that when pairing these devices with Home Assistant via the HomeKit Device integration, pairing intermittently fails in a variety of ways. 

- Sometimes Home Assistant starts pairing and then complains that the device is already paired
- Sometimes it all works perfectly
- Sometimes Home Assistant fails on step `04`

I've included a massive amount of logs in my original HomeSpan bug report, but the description of what's happening from the devs makes it sound like there's some sort of race condition in aiohomekit which is causing the pairing steps to happen in a random order (nondeterministically).

The HomeSpan issue link is here: https://github.com/HomeSpan/HomeSpan/issues/680

but the important part I think is here:

> Thanks -- these details are helpful, though I'm not sure there is much I can do. As you can see from your first log output, the first thing HA is doing is asking for a pair-verify. That makes no sense - it first needs to set up pairing before it can open a secure paired channel. However, this won't cause a problem for HomeSpan as it just reports the error and waits for the next input. Based on your log file, HA does send the correct pair-setup request, but waits for over a minute before sending. I have no idea why HA would wait so long. As you can see, it correctly send the 3 steps for pairing in the correct order (M1, M3, and then M5) and the device properly pairs.
>
> However, 10 seconds later HA seems to open a new connection and tries to pair again. Since the device is already paired, HomeKit responds with an error in accordance with the HAP protocol. Next, HA tries to create a secure connection using the steps for a pair-verify. Since the device is paired, this works and the verification completes. I do not know why HA does not think the device is paired since it has gone as far to open a secure connection.
>
> As you noted, the second log file shows a correct pairing and verification as HA sent all the right steps in the correct order.
>
> In the third log file, HA seems to be trying to verify a secure connection before it has finished all the pairing steps. HAP does not specify what is supposed to happen if a device interrupts a pair-setup with a misplaced pair-verify. I coded HomeSpan to reset the pairing procedure whenever that occurs so things can start fresh, but it looks like HA tries to continue the pairing setup by sending an M3 (which is the second step of pairing) --- by that time HomeSpan has already reset the pairing sequence and is expected to see M1 (which is the first step).
>
> Based on the above logs, it almost seems as if HA is running two parallel processes to try and pair/verify, such that depending on the exact timing, if one process completes everything works, but if they interfere, the behavior is indeterminant.

Could this be a bug in aiohomekit? Or maybe the Home Assistant integration itself? HomeSpan devices always pair flawlessly with "real" HomeKit controllers (e.g. via the Home app) and claim to be fully compliant with the spec, so I'm not sure what's going on

**Comment by Jc2k** [comment]
It sounds like pairing worked once and then you reset the esp but not the home assistant integration. So the existing pairing in ha is trying to establish a connection, but now you are trying to pair it again. So the device sees the results of 2 concurrent tasks - one trying to use the previous (stale) pairing, and one trying to make a new one.

**Comment by phybros** [comment]
That would make sense but I also tested it after removing the HA
integration and even restarting HA, along with totally wiping the ESP and
starting "from scratch" with completely different device IDs etc. Even when
doing that process multiple times it still produces these random results.

The "already paired" issue is only one of the ways it fails. The other main
one is the issue shown here


Again, this can happen after resetting, rebooting, removing the integration
and starting over etc.

**Comment by phybros** [comment]
Incidentally I did also try it on a completely different instance of HA on a different network at a different house and got the same issue the very first time trying to pair it.

Just to be sure, what are the steps you would suggest going through to get the HA integration to stop trying to contact the device after removing it from the integrations page?

**Comment by Jc2k** [comment]
The pair verify code path only happens when there is a pairing. It loads secrets from a config entry, and there is no config entry until pairing has happened.

It would probably fill your logs with exceptions if it tried.

That should mean that it'd be impossible to see pair verifys from ha if you removed the integration and then restarted ha to make sure it was gone. The restart shouldn't be needed but it's possible you've discovered an edge case where a faulty pairing can't be cleanly unloaded.

**Comment by Jc2k** [comment]
We know there are ~28k installs of this integration, and this is the first time I can remember this behaviour coming up, and you can recreate it in 2 distinct environments.

That makes me wonder if there is an environmental variable (eg we have had trouble with mdns repeaters in the past, and that's how paired/unpaired status is relayed, rather than via the api). We might want to examine logs from the zeroconf integration to make sure it's getting the right data there.

Duplicate device ids could also be a problem and cause this kind of confusion. Hopefully they are automated by homespan and fully random so I wouldn't expect that to be a problem.

**Comment by phybros** [comment]
Thanks for all this info. I also suspected network weirdness, which is why I tried it somewhere else with a super normal wifi/networking situation. And now that I'm thinking back maybe it _did_ work fine the very first time in that environment and then had issues subsequent times.... hmm. I'll go away and try to do a more scientific set of tests and let you know!

**Comment by phybros** [comment]
I tried just un-pairing and re-pairing from within HA a few times. When unpairing, it all works well, the HomeSpan devices sets itself back to unpaired etc, the integration disappears from HA. The device is immediately re-discovered by HA and I can re-pair no problem (MOST of the time), however it does put two things into the HA logs:

```
Logger: homeassistant.components.homekit_controller.connection
Source: components/homekit_controller/connection.py:782
Integration: HomeKit Device (documentation, issues)
First occurred: 2:22:31 PM (1 occurrences)
Last logged: 2:22:31 PM

HomeKit device update skipped as previous poll still in flight: CF:97:67:3A:BC:A6
```

and

```
Logger: aiohomekit.utils
Source: /usr/local/lib/python3.11/site-packages/aiohomekit/utils.py:45
First occurred: 2:22:35 PM (1 occurrences)
Last logged: 2:22:35 PM

Failure running background task: Task-4125
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/utils.py", line 40, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/connection.py", line 590, in _reconnect
    return await self._connect_once()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/connection.py", line 698, in _connect_once
    request, expected = state_machine.send(response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/protocol/__init__.py", line 596, in get_session_keys
    handle_state_step(response_tlv, TLV.M4)
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/protocol/__init__.py", line 90, in handle_state_step
    error_handler(tlv_dict[TLV.kTLVType_Error], f"step {expected_state}")
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/protocol/__init__.py", line 64, in error_handler
    raise AuthenticationError(stage)
aiohomekit.exceptions.AuthenticationError: step bytearray(b'\x04')
```

But as I said, the device is configured fine, and everything works as it should MOST of the time. Occasionally it will give the `step bytearray(b'\x04')` but if I try again 2 or 3 more times, getting that error in the UI each time, it eventually works

One intersting thing I noticed while looking at HomeSpan's debug logs is that even after I un-pair the device, and the integration vanishes from HA, the device is still receiving HTTP requests periodically like this:

```
2023-11-11 14:34:04 --> ** Client #12 Connected: (87 sec) 192.168.86.201 on Socket 3/16
2023-11-11 14:34:04 --> 
2023-11-11 14:34:04 --> <<<<<<<<< 192.168.86.201 <<<<<<<<<
2023-11-11 14:34:04 --> POST /pair-verify HTTP/1.1
2023-11-11 14:34:04 --> Host: 192.168.86.46
2023-11-11 14:34:04 --> Content-Length: 37
2023-11-11 14:34:04 --> Content-Type: application/pairing+tlv8
2023-11-11 14:34:04 --> ------------ END BODY! ------------
2023-11-11 14:34:04 --> STATE(1) 01
2023-11-11 14:34:04 --> PUBKEY(32) 7D278B1D4A959D2C111F91B1D4ABB04220BCF7CFA38E29A0B14F16BA70DBBE59
2023-11-11 14:34:04 --> -------
2023-11-11 14:34:04 --> ----- END TLVS! ------------
2023-11-11 14:34:04 --> In Pair Verify #12 (192.168.86.201)...
2023-11-11 14:34:04 --> *** ERROR: Device not yet paired!
2023-11-11 14:34:04 --> 
2023-11-11 14:34:04 --> 
2023-11-11 14:34:04 --> >>>>>>>>>> 192.168.86.201 >>>>>>>>>>
2023-11-11 14:34:04 --> HTTP/1.1 200 OK
2023-11-11 14:34:04 --> Content-Type: application/pairing+tlv8
2023-11-11 14:34:04 --> Content-Length: 6
2023-11-11 14:34:04 --> 
2023-11-11 14:34:04 --> STATE(1) 02
2023-11-11 14:34:04 --> ERROR(1) 01
2023-11-11 14:34:04 --> ------------ SENT! --------------
```

Almost like HA is still doing things in the background even though the integration is gone. This still happens after I reboot the ESP device also. It wakes up and starts getting these requests. The IP ending `201` is my home assistant server BTW.

If I restart HA in this situation, the HTTP requests stop, and they don't start again once HA is back up.

After HA is back up, I try to pair and almost always get the "device is already paired", and I can see in HomeSpan's logs that HA is requesting to pair, pairing, and then requesting to pair a second time, resulting in the error.

The second set of tests I did also involved wiping the ESP device and having it re-generate a new unique device ID. Each time I did this, I also restarted my HA instance to get rid of any cached zeroconf discovery things. This seemed most successful when I wiped the ESP and also powered it totally off during the HA restart. Even then, sometimes there was a device "detected" by HA. Definitely seems like some mdns/zeroconf things maybe?

A couple of times I got this, if that helps.

```
Logger: aiohomekit.utils
Source: /usr/local/lib/python3.11/site-packages/aiohomekit/utils.py:45
First occurred: 2:16:39 PM (2 occurrences)
Last logged: 2:18:15 PM

Failure running background task: Task-2638
Failure running background task: Task-3279
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/pairing.py", line 140, in _ensure_connected
    await connection.ensure_connection()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/connection.py", line 313, in ensure_connection
    await asyncio.shield(self._connector)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/pairing.py", line 139, in _ensure_connected
    async with asyncio_timeout(10):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/utils.py", line 40, in _handle_task_result
    task.result()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/pairing.py", line 421, in _process_config_changed
    await self.list_accessories_and_characteristics()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/pairing.py", line 177, in list_accessories_and_characteristics
    await self._ensure_connected()
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/pairing.py", line 146, in _ensure_connected
    raise AccessoryDisconnectedError(
aiohomekit.exceptions.AccessoryDisconnectedError: Timeout while waiting for connection to device 192.168.86.46:80
```

**Comment by bdraco** [comment]
It looks like HA isn't fully shutting down the connection when its unpaired.

**Comment by phybros** [comment]
Is there anything I can do to confirm that @bdraco ?

**Comment by Jc2k** [comment]
If it's still doing pair verify after removing the integration and stopping after a restart then it's pretty much confirmed.

It's probably not been a problem before because most users add it once and don't need to remove it and add it again.

**Comment by phybros** [comment]
OK should I report this to HA then? What's the next thing to do for this issue?

**Comment by Jc2k** [comment]
No reporting it there would just ping the same people that you are speaking to here :) Just need to wait for someone to have time to look into it.

**Comment by phybros** [comment]
Hey there! I have definitively confirmed that this can happen if the device is brand new and has never been paired with HA. Also this was on a completely fresh HA that has never paired any devices before. So it seems like it's not just pair-unpair scenario from above.

**Comment by Jc2k** [comment]
When this happens, could it be that an ip/port from a previous experiment is reused, even if the device id is changed? If that's the case then it's probably "just" a leak in HA where an old connection/pairing is still trying to connect. IIRC, there is a background loop that will try to keep the connection alive at all times (to receive an event stream).

**Comment by M10tech** [comment]
Maybe this is the case, but that loop then needs to be removed at unpair or not matching mdns info.
Also, that loop is creating many TCP sessions where step PV1/2 is sent, answer is received, but then it just sits there, not releasing the TCP session.

Based on the observation, there would be a first loop that never gets removed, and a second one started with the new pairing and on restart with a pairing registered.

I read IP/port being reused as the device IP and port, and yes, that remains the same at all times as it should/would.
So, the loop should re-assess the mdns info from time to time or based on a push and check that the ID is not the right one anymore.

Also, that loop seems unaware of the existence of one 'alive' HK session already, and that as well should shut it up.
That could be if there are two loops.

Either way, I don't mind to write a bit of code or dig for the root cause, as long as I know it will result in an actual fix in the eco-system. If I know you are keen to get this solved as well and give me the occasional hint of where to look, I can chip in I guess.

**Comment by Jc2k** [comment]
You are getting ahead a bit. Of course it should be removed. I'm trying to localise where we look. If you are reusing the ip and port for multiple "different" devices (including same physical device but reset with a different device id) then I have a good place to start looking.

If the problem "goes away" when you remove all pairings for that ip/port in HA and restart HA, this seems more likely to be the case.

And finally, the fact that this is more common with "home brew" stuff lends itself to that explanation too. Because if it was an off the shelf device you'd pair it once and that'd be that, it's either working or it wouldn't. But when you are flashing something over and over you are suddenly almost guaranteed to hit this. Explaining the distribution of users with this problem.

We have an api that allows us to take a reference to the HA wide zeroconf instance and we listen to hap events constantly. We already have hooks in place to notify ip/port changes and use them immediately. We don't proactively stand down if an mdns record goes away. This was a deliberate choice because we have found mdns to be very flakey for some users.

Maybe failed authentication probably should just cause the retry loop to fail? My only concern would be bad (but otherwise certified and working) devices using auth errors to signal transient errors.

However, HA should have removed the pairing and that should have cancelled the loop.

But now I'm getting ahead of myself.

With a clean HA, and debug logs on, pair to one of your devices. While the device is on, remove the pairing from HA. Does it stop trying to connect?

If it does, repeat this a bunch of times.

If it still does, try again but this time turn your device off after pairing and before removing it from HA. Does the background connection attempt continue now?

**Comment by Jc2k** [comment]
I'll wait for you to run my tests, then.

I can see code that tries close down the connection when you remove a device from HA. However if that fails (like you reset your device already or it's offline) I can see ways it would cause the behaviour you are seeing.

And yes, we use the device id to route mdns events to the pairing they are about.

**Comment by M10tech** [comment]
```
I am sure the unpair did not fail, since my logs show it explicitly and the device chooses a new ID.
To be honest, I do not see an added value in repeating the tests you proposed, since I already did them.
If you hint me to the relevant bits where this loop lives, I'll do code review and see if that makes a difference.
Including tweaking code etc. during the tests.

Is there a way for me to share existing logs? It feels a shame to paste 5k lines of log here as a comment...

**Comment by M10tech** [comment]
Wow, that is lightning fast fixing! Thanks a lot.
And nice that 343 was closed by 433 ;-)

When does this end up in a HA release? (assuming happy flow)

**Comment by Jc2k** [comment]
It's on HA dev branch now. Normally that goes into beta on the last Wednesday of the month and then ships on the first Wednesday of the month.

We've tagged it for backporting, so if there is another point release before the beta it will be cherry picked into that. Those are more adhoc, depends on how many patches have built up.
