### ISSUE TITLE
BLE: splat during init, subscriptions

### ISSUE THREAD

**Issue by roysjosh** [Jc2k/aiohomekit#82]
My Elements Border Router has died so I've been playing around with BLE. I edited `config/.storage/core.config_entries` to swap the transport from CoAP to BLE and got this splat soon after Pair-Verify:

```
2022-03-30 20:53:48 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File ".../aiohomekit/controller/ble/pairing.py", line 376, in subscribe
    await self._ensure_connected()
  File ".../aiohomekit/controller/ble/pairing.py", line 176, in _ensure_connected
    for (aid, iid) in self.subscriptions:
RuntimeError: Set changed size during iteration
```

**Comment by Jc2k** [comment]
Have wrapped a `list()` around it in `dev`. Not convinced that is the full fix, but we had to do the same thing in IP.
