### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#85]
```
2022-05-09 19:41:59 ERROR (MainThread) [aiohomekit.controller.ip.connection] Unexpected error whilst trying to connect to accessory. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/connection.py", line 540, in _reconnect
    return await self._connect_once()
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/connection.py", line 648, in _connect_once
    await self.owner.connection_made(True)
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/pairing.py", line 103, in connection_made
    await self.subscribe(self.subscriptions)
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/pairing.py", line 299, in subscribe
    return await self._update_subscriptions(characteristics, True)
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/pairing.py", line 330, in _update_subscriptions
    "characteristics": [
  File "/usr/local/lib/python3.9/site-packages/aiohomekit/controller/ip/pairing.py", line 330, in <listcomp>
    "characteristics": [
RuntimeError: Set changed size during iteration
```

This happened while testing something else. Documenting it now so I don't forget

**Comment by Jc2k** [comment]
This is also happening in #82, thought it was specific to BLE but maybe not. Pretty sure it's a regression either way.
