### ISSUE TITLE
Bluetooth debugging

### ISSUE THREAD

**Issue by Jc2k** [Jc2k/aiohomekit#96]
# Model not set

This hits everything. But this was the only patch needed to be able to pair an Eve Motion.

It's not part of the advertisement, we have to read a characteristic. 

```
diff --git a/homeassistant/components/homekit_controller/config_flow.py b/homeassistant/components/homekit_controller/config_flow.py
index ac840eb068..86334f14b1 100644
--- a/homeassistant/components/homekit_controller/config_flow.py
+++ b/homeassistant/components/homekit_controller/config_flow.py
@@ -111,7 +111,7 @@ class HomekitControllerFlowHandler(config_entries.ConfigFlow, domain=DOMAIN):
         if user_input is not None:
             key = user_input["device"]
             self.hkid = self.devices[key].description.id
-            self.model = self.devices[key].description.model
+            self.model = getattr(self.devices[key].description, "model", "Bluetooth device")
             self.name = self.devices[key].description.name
 
             await self.async_set_unique_id(
```

## Failure during pairing

This was with a Nanoleaf Essentials Light strip.

Device rejects our pairing attempt by closing the connection:

```
2022-07-14 21:23:34.351 DEBUG (MainThread) [aiohomekit.protocol.tlv] sending [
  6: (1 bytes/<class 'bytearray'>) 0x01
  3: (32 bytes/<class 'bytes'>) b'\xf8\xe2|\xc0\x81~\xfb\xdaU.mW\x86\x12\xb3\x084\xf3?\xdd\x8e<\x92\xc3\x00\x88\xfd\x04\x97V\x81\x0b'
]

2022-07-14 21:23:34.351 DEBUG (MainThread) [aiohomekit.controller.ble.client] Using fragment size: 101
2022-07-14 21:23:34.351 DEBUG (MainThread) [aiohomekit.controller.ble.client] Writing fragment: b'\x00\x02\xf2#\x00*\x00\t\x01\x01\x01%\x06\x01\x01\x03 \xf8\xe2|\xc0\x81~\xfb\xdaU.mW\x86\x12\xb3\x084\xf3?\xdd\x8e<\x92\xc3\x00\x88\xfd\x04\x97V\x81\x0b'
2022-07-14 21:23:35.350 DEBUG (MainThread) [aiohomekit.controller.ble.pairing] Session closed
2022-07-14 21:23:35.351 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/Users/john/Projects/home-assistant/homeassistant/components/homekit_controller/config_flow.py", line 371, in async_step_pair
    return await self._entry_from_accessory(pairing)
  File "/Users/john/Projects/home-assistant/homeassistant/components/homekit_controller/config_flow.py", line 484, in _entry_from_accessory
    accessories = await pairing.list_accessories_and_characteristics()
  File "/Users/john/Projects/home-assistant/venv/lib/python3.9/site-packages/aiohomekit/controller/ble/pairing.py", line 283, in list_accessories_and_characteristics
    await self._ensure_connected()
  File "/Users/john/Projects/home-assistant/venv/lib/python3.9/site-packages/aiohomekit/controller/ble/pairing.py", line 174, in _ensure_connected
    await self._async_pair_verify()
  File "/Users/john/Projects/home-assistant/venv/lib/python3.9/site-packages/aiohomekit/controller/ble/pairing.py", line 204, in _async_pair_verify
    session_id, derive = await drive_pairing_state_machine(
  File "/Users/john/Projects/home-assistant/venv/lib/python3.9/site-packages/aiohomekit/controller/ble/client.py", line 147, in drive_pairing_state_machine
    response = await char_write(
  File "/Users/john/Projects/home-assistant/venv/lib/python3.9/site-packages/aiohomekit/controller/ble/client.py", line 114, in char_write
    data = await ble_request(
  File "/Users/john/Projects/home-assistant/venv/lib/python3.9/site-packages/aiohomekit/controller/ble/client.py", line 84, in ble_request
    data = await client.read_gatt_char(handle)
  File "/Users/john/Projects/home-assistant/venv/lib/python3.9/site-packages/bleak/backends/corebluetooth/client.py", line 261, in read_gatt_char
    output = await self._delegate.read_characteristic(
  File "/Users/john/Projects/home-assistant/venv/lib/python3.9/site-packages/bleak/backends/corebluetooth/PeripheralDelegate.py", line 144, in read_characteristic
    return await asyncio.wait_for(future, timeout=5)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
bleak.exc.BleakError: disconnected
```

**Comment by bdraco** [comment]
This was already solved
