### ISSUE TITLE
Test if we can remove the resume pairing fallback

### ISSUE THREAD

**Issue by bdraco** [Jc2k/aiohomekit#99]
https://github.com/Jc2k/aiohomekit/pull/97#discussion_r922296755

**Comment by bdraco** [comment]
I actually hit this earlier today when testing

**Comment by bdraco** [comment]
Now if I had saved the trace that would have been even better

**Comment by Jc2k** [comment]
Was just coming to ask for a trace haha

**Comment by bdraco** [comment]
Maybe I did in the terminal history...

**Comment by bdraco** [comment]
No dice, but I'm still it will happen again and I'll be awake enough to remember to save it

**Comment by bdraco** [comment]
```
2022-07-16 17:30:12.515 ERROR (MainThread) [aiohomekit.utils] Failure running background task: Task-9948
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 299, in _async_pair_verify
    session_id, derive = await drive_pairing_state_machine(
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 214, in drive_pairing_state_machine
    request, expected = state_machine.send(TLV.decode_bytes(response))
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 584, in get_session_keys
    handle_state_step(response_tlv, TLV.M4)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 87, in handle_state_step
    error_handler(tlv_dict[TLV.kTLVType_Error], f"step {expected_state}")
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/protocol/__init__.py", line 61, in error_handler
    raise AuthenticationError(stage)
aiohomekit.exceptions.AuthenticationError: step bytearray(b'\x04')
```

**Comment by bdraco** [comment]
This was done
